### ISSUE TITLE
MetadataTable.DataType oDataType = table.GetDataType(); only returns type CHARACTER or DATE for tables...

### ISSUE THREAD

**Issue by robdob** [NationalAssociationOfRealtors/libRETS#10]
MetadataTable.DataType oDataType = table.GetDataType(); 
only returns type CHARACTER or DATE for tables... even though the metadata is DECIMAL or something else..  

I'm using the dotnet lib within C#

http://nationalassociationofrealtors.github.io/libRETS/downloads/

**Comment by robdob** [comment]
Hi,

I'm using LibRets via C# and am trying to perform an incremental query on the rets server..  according to the documentation that treb gave me they say the following:

*"To complete an Incremental download (Cumulative download of up to a maximum of 10 days of Available
-1- connect to the Rets server
-2- Set query (to obtain data less than 10 days old use both, ‘Updated timestamp’ (timestamp_sql) and ‘IDX updated date’ (idx_dt) using equivalent of the SQL operator ‘OR’ in the RETS client"*

**therefore I have tried the following:**

SearchRequest searchRequest = session.CreateSearchRequest(
                                                    "Property",
                                                    "ResidentialProperty",
                                                    "(timestamp_sql=2015-01-25T00:00:00+ OR idx_dt=2015-01-25+)");

                searchRequest.SetStandardNames(true);
                searchRequest.SetOffset(SearchRequest.OFFSET_NONE);
                searchRequest.SetCountType(SearchRequest.CountType.RECORD_COUNT_AND_RESULTS);

                SearchResultSet results = session.Search(searchRequest);

**but I'm getting the following error back when looking at the trace log..**

Class=ResidentialProperty&Count=1&Format=COMPACT-DECODED&Query=(timestamp_sql%3d2015-01-25T00:00:00%2b OR idx_dt%3d2015-01-25%2b)&QueryType=DMQL2&SearchType=Property&StandardNames=1
<<< Received
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
RETS-Version: RETS/1.5
cache-control: private
Server: StratusRETS/1.7
Content-Type: text/xml;charset=utf-8
Transfer-Encoding: chunked
Date: Wed, 28 Jan 2015 15:22:54 GMT

3c
<RETS ReplyCode="20206" ReplyText="Invalid DMQL query (0)"/>


**Could you please tell me how to resolve this, i.e. what is wrong with my syntax...  thanks,**

**Comment by KidSysco** [comment]
Hi Robdob,

I think I have seen some of your comments in here before. I use the RETS
connector to help me put together queries.

http://www.reso.org/tools

I could tell you that I "think" it doesn't like the OR in the way you have
presented it but I could be wrong and I dont want to lead you wrong.

The RETS connector will give you a UI to build and submit queries to your
RETS server. I would build the query you want in there, make sure you get
the data back you want then look at the query it generated and submitted to
the RETS server. It displays the RETS query in the little window every time
a query runs.

I have used this technique many times to correct my query syntax.

Hope this helps!

- kid

**Comment by bwolven** [comment]
Your query should be something like this:

(timestamp_sql=2015-01-25T00:00:00+)|(idx_dt=2015-01-25+) 

“|” = OR
“,”  = AND
“~” = NOT

Bruce

**Comment by robdob** [comment]
@KidSysco 

thank you for taking the time to answer my question...  I think I figures it out...  I had to change:

searchRequest.SetStandardNames(true);

to

searchRequest.SetStandardNames(false);

so that it would recognize my query field by the SQL_name..

after this change it worked okay...  I will take a look at the rets connector as you have suggested...

**Comment by KidSysco** [comment]
Wow, yea, I was way off. But this makes sense and this post could help some
other poor soul out there someday. Glad its working! Woot woot!

**Comment by alexsmartens** [comment]
Hi there,
I'm trying to set up a query to select data based on `timestamp_sql` and `idx_dt` however it fails with `ReplyCode="20202" ReplyText="Invalid Select: The Select statement contains field names that are not recognized by the server.`. Could you help to figure out what the problem is?

More details:
query `(timestamp_sql=2020-09-09T00:00:00+)` works just fine however both `(idx_dt=2020-09-09+)` and `(timestamp_sql=2020-09-09T00:00:00+)|(idx_dt=2020-09-09+)` fail with the same error message.
