### ISSUE TITLE
results.GetCount() is 659,but results.GetColumns() has nothing

### ISSUE THREAD

**Issue by liaicheng** [NationalAssociationOfRealtors/libRETS#15]
python2.7
librest:1.6.1
code like that:

`request = rets_session.CreateSearchRequest(res_name, cls_name, query_str)`
`results = rets_session.Search(request)`
`mc.logger.debug( "Record count: " + results.GetCount()`)   #value is 659

`columns = results.GetColumns()`
`mc.logger.debug( "count: " + len(columns0)`   #value is 0!!!`

what's wrong with my way?
thanks!

**Comment by ktgeek** [comment]
your last two lines of code use different columns variables if its exactly as written.
