### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by KidSysco** [NationalAssociationOfRealtors/libRETS#16]
There used to be a place to download the compiled binaries. But I cannot find it. Something has happened and my LibRETS queries suddenly stopped working. Perhaps I need an update to libRETS but I cannot find the dlls.

**Comment by KidSysco** [comment]
Here is one error I get...

Inner Exception Source

librets-dotnet

Message

The data stream ended before the XML parser could parse everything. This can happen if the network connection terminates before all the data has been received.

**Comment by KidSysco** [comment]
Also, I might mention that the server was replaced without my knowing, that is when this issue surfaced. Ever since, I get either this message or 0 results on queries that once worked great. Sorry for so many messages, I am just thinking out loud.

**Comment by dconroy** [comment]
are you looking for this? 

https://github.com/NationalAssociationOfRealtors/libRETS/releases

**Comment by KidSysco** [comment]
yep thanks!
