### ISSUE TITLE
NodeJS

### ISSUE THREAD

**Issue by lance0821** [NationalAssociationOfRealtors/libRETS#17]
I was able to build librets on OSX El Captain, referencing the expat and boost library paths with ./configure, then adding -m32 to clang and ldflags in the makefile. I built librets with sudo make, then sudo make install, everything looks fine no errors I have a file librets.node in my  build/Release directory how do I install this as a global npm module?

**Comment by KidSysco** [comment]
You should probably look here...

https://github.com/retsr/rets.js

I assume this repo is for the libRETS library only. Someone else will package up an npm module for it.

**Comment by ktgeek** [comment]
> On Dec 15, 2015, at 1:18 PM, Lance <notifications@github.com> wrote:
> I was able to build librets on OSX El Captain, referencing the expat and boost library paths with ./configure, then adding -m32 to clang and ldflags in the makefile. I built librets with sudo make, then sudo make install, everything looks fine no errors I have a file librets.node in my build/Release directory how do I install this as a global npm module?
> 
> 

One of the last things i worked on before I left NAR!  I'm glad someone is using it.

You don't need npm for this.  You just need to put it somewhere on the node library search path.  I'm not much of a js/node guy, but https://gist.github.com/branneman/8048520 <https://gist.github.com/branneman/8048520> seems like a pretty good rundown of things you could do. 

Keith

-- 
 Keith T. Garner                                        kgarner@kgarner.com
                "Make no little plans; they have no magic to
                   stir men's blood." - Daniel H. Burnham

**Comment by KidSysco** [comment]
Yea I just re-read the readme from the link I posted. It says it is not a wrapper for libRets.
