### ISSUE TITLE
node-gyp

### ISSUE THREAD

**Issue by briviere** [NationalAssociationOfRealtors/libRETS#18]
Trying to build the librets node.js addon I get the following error:

C:\Users\xxxxxxx\libRETS\project\swig\node.js>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@4.2.2 | win32 | x64
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  librets_wrap.cpp
c1xx : fatal error C1083: Cannot open source file: '..\librets_wrap.cpp': No su
ch file or directory [C:\Users\rxxxxxxx\libRETS\project\swig\node.js\build\libre
ts.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\Users\xxxxxxx\libRETS\project\swig\node.js
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

**Comment by ktgeek** [comment]
The node-gyp stuff only support UNIXes right now.  (Well, tested on Linux and OS X.)

To make it work on windows it'd probably need some tweaking.  You'd also need to build libRETS proper first.  And execute the swig stuff to create binding code... if you're going to attempt it, look at the Makefile.vc stuff for the other swig bound languages.

**Comment by briviere** [comment]
I used Unix and realized that I did not have SWIG installed.  I'm able to build successfully under Unix and run the not modules successfully.

thanks

Brian
