### ISSUE TITLE
search.js is failing

### ISSUE THREAD

**Issue by briviere** [NationalAssociationOfRealtors/libRETS#19]
I'm not sure why the search is failing, not log log information available.

/libRETS/build/swig/node.js $ node search.js 
Action: 
Requested RETS version: RETS/1.5
Actual RETS version: RETS/1.5
Exception: Error: RetsReplyException

thanks

Brian

**Comment by bwolven** [comment]
Are you sending “RETS/15” or “RETS/1.5” which would be a valid RETS version?

Bruce

From: Brian Riviere 
Sent: Thursday, January 07, 2016 5:26 PM
To: NationalAssociationOfRealtors/libRETS 
Subject: [libRETS] search.js is failing (#19)

I'm not sure why the search is failing, not log log information available

/libRETS/build/swig/nodejs $ node searchjs 
Action: 
Requested RETS version: RETS/15
Actual RETS version: RETS/15
Exception: Error: RetsReplyException

thanks

Brian

**Comment by briviere** [comment]
I'm not setting any version.

 var session = new librets.RetsSession("
http://rets.mresdms.com:8080/rets/rets/login");

    if (!session.Login("xxxxxxxxxxxx", "xxxxxxxxxxxxxxx"))
    {
        console.log("Invalid login");
        process.exit(-1);
    }

    *console.log("Action: " + session.GetAction());*
*    console.log("Requested RETS version: " +
session.RetsVersionToString(session.GetRetsVersion()));*
*    console.log("Actual RETS version: " +
session.RetsVersionToString(session.GetDetectedRetsVersion()));*

    var request = session.CreateSearchRequest("Property", "RES",
"(ListPrice=300000-)");
    request.SetStandardNames(false);
    request.SetSelect("ListingID,ListPrice,Bedrooms,City");
    request.SetLimit(librets.SearchRequest.LIMIT_DEFAULT);
    request.SetOffset(librets.SearchRequest.OFFSET_NONE);
    request.SetCountType(librets.SearchRequest.RECORD_COUNT_AND_RESULTS);
    request.SetFormatType(librets.SearchRequest.COMPACT);
    results = session.Search(request);

    while (results.HasNext())
    {
console.log("ListingID: " + results.GetString("ListingID"));
console.log("ListPrice: " + results.GetString("ListPrice"));
console.log(" Bedrooms: " + results.GetString("Bedrooms"));
console.log("     City: " + results.GetString("City"));
console.log();
    }
}
catch(e)
{
    console.log("Exception: " + e);
}
finally
{
    session.Logout();
}var session = new librets.RetsSession("
http://rets.mresdms.com:8080/rets/rets/login");

**Comment by briviere** [comment]
Actually the version is RETS/1.5

Action:
Requested RETS version: RETS/1.5
Actual RETS version: RETS/1.5
Exception: Error: RetsReplyException

**Comment by briviere** [comment]
I tried the python search.js and it works fine. 

brian

**Comment by briviere** [comment]
Looking at the call stack it appears to be a timeout issue:

(anonymous function) (search.js:37)
Module._compile (module.js:435)
Module._extensions..js (module.js:442)
Module.load (module.js:356)
Module._load (module.js:311)
Module.runMain (module.js:467)
listOnTimeout (timers.js:92)

**Comment by jazzklein** [comment]
Is this still an open issue? If so, log the http and let's examine the RetsReply output.

**Comment by briviere** [comment]
Hello Bruce

Yes it is still an issue.  I'm not sure what you mean log the http?  Is
there a way to enable logging in libRets?

thanks

Brian

**Comment by briviere** [comment]
Is there any suggestion on how I would go about debugging the node.js / Swig search issue?  I had mentioned earlier the both the python and perl search samples are working fine.

thanks

Brian

**Comment by jazzklein** [comment]
A RetsReplyException implies the response from the server is malformatted. We need to examine the http logs to be sure.

http://www.crtlabs.org/libRETS/documentation/api/classlibrets_1_1_rets_session.html#aaf72eb346835bde69fc1d7e4d3dca550

**Comment by briviere** [comment]
Hello 

I turned on logging and it's appears to be complaining about ListingID (<RETS ReplyCode="20202" ReplyText="Invalid Select: ListingID"/>).  I'm not sure why since it does exist in the "RES" class (Table name: MLSNUM [ListingID] (1)).

* Found bundle for host rets.mresdms.com: 0x2093390
* Re-using existing connection! (#0) with host rets.mresdms.com
* Connected to rets.mresdms.com (65.110.168.236) port 8080 (#0)
* Server auth using Digest with user 'LDON-xxxxxxxxxxx'

>>> Sent
POST /rets/rets/search HTTP/1.1
Authorization: Digest username="LDON-xxxxxxxxxxx", realm="RETS Server", nonce="f62a544cfc28c34f64417939db98e9f9", uri="/rets/rets/search", cnonce="NWIzZTI1NTE4ZGE2MGU1NzAwMDFhNWQ1MDAwMzJjZmE=", nc=00000002, qop=auth, response="bb5a761aa2041146a2068c28af715414", opaque="108576778e7714b2adf6eb50b7f5cd30"
Host: rets.mresdms.com:8080
Accept: */*
Cookie: JSESSIONID=1A39C5186B3E65405EAAAEC7804D2F98
RETS-Version: RETS/1.5
User-Agent: librets/1.6.3-SNAPSHOT
X-Librets-Version: 1.6.3-SNAPSHOT, libCURL - libcurl/7.35.0 GnuTLS/2.12.23 zlib/1.2.8 libidn/1.28 librtmp/2.3
Content-Length: 153
Content-Type: application/x-www-form-urlencoded

Class=RES&Count=1&Format=COMPACT&Query=(ListPrice%3d300000-)&QueryType=DMQL2&SearchType=Property&Select=ListingID,ListPrice,Bedrooms,City&StandardNames=0* upload completely sent off: 153 out of 153 bytes

<<< Received
HTTP/1.1 200 OK
RETS-Version: RETS/1.5
Content-Type: text/xml
Content-Length: 65
Date: Tue, 26 Jan 2016 13:15:09 GMT
* Server Apache Coyote/1.0 is not blacklisted

<<< Received
Server: Apache Coyote/1.0

<RETS ReplyCode="20202" ReplyText="Invalid Select: ListingID"/>
* Connection #0 to host rets.mresdms.com left intact
* Found bundle for host rets.mresdms.com: 0x2093390
* Re-using existing connection! (#0) with host rets.mresdms.com
* Connected to rets.mresdms.com (65.110.168.236) port 8080 (#0)
* Server auth using Digest with user 'LDON-xxxxxxxxxxx'

>>> Sent
GET /rets/rets/logout HTTP/1.1
Authorization: Digest username="LDON-xxxxxxxxxxx", realm="RETS Server", nonce="f62a544cfc28c34f64417939db98e9f9", uri="/rets/rets/logout", cnonce="NWIzZTI1NTE4ZGE2MGU1NzAwMDFhNWQ1MDAwMzJjZmE=", nc=00000003, qop=auth, response="ea5d8fa1c412904575e276d2295efdf0", opaque="108576778e7714b2adf6eb50b7f5cd30"
Host: rets.mresdms.com:8080
Accept: */*
Cookie: JSESSIONID=1A39C5186B3E65405EAAAEC7804D2F98
RETS-Version: RETS/1.5
User-Agent: librets/1.6.3-SNAPSHOT
X-Librets-Version: 1.6.3-SNAPSHOT, libCURL - libcurl/7.35.0 GnuTLS/2.12.23 zlib/1.2.8 libidn/1.28 librtmp/2.3


<<< Received
HTTP/1.1 200 OK
RETS-Version: RETS/1.5
Content-Type: text/xml
Content-Length: 186
Date: Tue, 26 Jan 2016 13:15:09 GMT
* Server Apache Coyote/1.0 is not blacklisted

<<< Received
Server: Apache Coyote/1.0

<?xml version="1.0"?>
<RETS ReplyCode="0" ReplyText="Operation Successful">
<RETS-RESPONSE>
ConnectTime = 10457
Billing = 73.20
SignOffMessage = Goodbye
</RETS-RESPONSE>
</RETS>
* Connection #0 to host rets.mresdms.com left intact

**Comment by briviere** [comment]
The search is working now.  I needed to specify correct table names.

thanks

Brian
