### ISSUE TITLE
Support for HTTPS TLS 1.2 Connections

### ISSUE THREAD

**Issue by bwolven** [NationalAssociationOfRealtors/libRETS#21]
The latest version of LIBRETS is built using: X-Librets-Version: 1.6.2, libCURL - libcurl/7.35.0 OpenSSL/1.0.0a
Is there someone that could do a build of LIBRETS with more recent versions of LIbCURL and OpenSSL that support TLS 1.2 connections?

**Comment by jazzklein** [comment]
What platform?

**Comment by bwolven** [comment]
Yes I'm mainly concerned about LIBRETS windows builds, but other platforms would probably benefit too if they use the common libraries since companies are getting away from anything SSL less than TLS 1.2.
We had a developer try building it but from what I was told it can be a major undertaking to get everything setup and building properly.

**Comment by jazzklein** [comment]
He's right. As I said above, it isn't something I relish doing. The last time I refreshed things it took a couple of weeks to get everything right. Since I do this on my own time these days, it isn't something I'm likely to do in the near future.

**Comment by amcelmon** [comment]
Hey all. The CoreLogic Trestle platform requires TLS 1.2 and we have quite a few users who have reported this flaw. We're looking into assisting with this effort, however, I wanted to note the issue as there may be an resurgence in reports of this issue.

**Comment by jbramleycl** [comment]
FYI, the latest commits include compiling against a more recent version of openssl and therefore support TLS1. 2
