### ISSUE TITLE
GetObject with Search request

### ISSUE THREAD

**Issue by briviere** [NationalAssociationOfRealtors/libRETS#24]
Hello I'm perform to call the GetObject after doing search for multiple listing.  If I only have one search element to process the GetObject work, anymore it fails.

  console.log("Action: " + session.GetAction());
    console.log("Requested RETS version: " + session.RetsVersionToString(session.GetRetsVersion()));
    console.log("Actual RETS version: " + session.RetsVersionToString(session.GetDetectedRetsVersion()));

    var request = session.CreateSearchRequest("Property", "RES", "(ListPrice=300000-)");
    //var request = session.CreateSearchRequest("Property", "RES", "(MLSNUM=523829)");
    
    request.SetStandardNames(false);
    request.SetSelect("ListPrice,Bedrooms,PHOTO_COUNT,CityRets,VTourUrl,MLSNUM,PictureId,Latitude,Longitude,ListAgentEmail,LEGALDESC,StreetName,Province,PROPCODE");
    request.SetLimit(librets.SearchRequest.LIMIT_DEFAULT);
    request.SetOffset(librets.SearchRequest.OFFSET_NONE);
    request.SetCountType(librets.SearchRequest.RECORD_COUNT_AND_RESULTS);
    request.SetFormatType(librets.SearchRequest.COMPACT);
    results = session.Search(request);

    console.log("exports.create = {");
    console.log("   Residential: [");
    
    var first = true;
        
    while (results.HasNext())
    {
         // Gets the large image
        var get_object_request = new librets.GetObjectRequest("Property", "Photo");
    
        var locationPhotoUrls = [];
        var locationThumbUrls = [];
        
        var pictureId = results.GetString("PictureId");
        get_object_request.AddAllObjects(pictureId);
        get_object_request.SetLocation(true);
            
       // Rets exception happens here
        var get_object_response = session.GetObject(get_object_request);
        
        var object_descriptor = get_object_response.NextObject();
    
        // Uncomment to write all images to cloud.
        while (object_descriptor)
        {
            locationPhotoUrls.push(object_descriptor.GetLocationUrl());
            object_descriptor = get_object_response.NextObject();
        }
        
        get_object_request = new librets.GetObjectRequest("Property", "Thumbnail");
        
        get_object_request.AddAllObjects(pictureId);
        get_object_request.SetLocation(true);
        
        var get_object_response = session.GetObject(get_object_request);
    
        var object_descriptor = get_object_response.NextObject();
    
        // Uncomment to write all images to cloud.
        while (object_descriptor)
        {
            locationThumbUrls.push(object_descriptor.GetLocationUrl());
            object_descriptor = get_object_response.NextObject();
        }
        
        console.log("       {");
        console.log(
            "           'MLSNUM': '"+ results.GetString("MLSNUM") + "'" +
            ", 'LocationPhotoUrls': '" + locationPhotoUrls.toString() + "'" +
            ", 'LocationThumbUrls': '" + locationPhotoUrls.toString() + "'" + 
            ", 'ListPrice': '" + results.GetString("ListPrice") + "'" +
            ",'Bedrooms': '" + results.GetString("Bedrooms") + "'" +
            ",'PictureID': '" + results.GetString("PictureId") + "'" +
            ",'Longitude': '" + results.GetString("Longitude") + "'" +
            ",'Latitude': '" + results.GetString("Latitude") + "'" +
            ",'ListAgentEmail': '" + results.GetString("ListAgentEmail") + "'" +
            ",'PHOTO_COUNT': '" + results.GetString("PHOTO_COUNT") + "'" +
            ",'CityRets': '" + results.GetString("CityRets") + "'" +
            ",'VTourUrl': '" + results.GetString("VTourUrl") + "'" +
            ",'PROPCODE': '" + results.GetString("PROPCODE") + "'" +
            ",'StreetName': '" + results.GetString("StreetName") + "'" +
            ",'Province': '" + results.GetString("Province") + "'"
        );
        console.log("       }");
    }
    console.log("   ]");
    console.log("};");

**Comment by jazzklein** [comment]
I don't speak node, so take my comments with a grain of salt.  You are obtaining "PictureId" and asking for all objects associated with it. Because the noun "PictureId" is singular ... I'm thinking there is a 1:1 relationship between IDs and images and libRETS is fetching exactly what you're asking. On the other hand, if PictureId is in fact an array of picture IDs, you'll need to parse it and provide the IDs one by one through the AddObject() API. AddAllObjects() only works using the designated KeyField (usually the listing ID, but check the metadata).
