### ISSUE TITLE
Fatal error: No matching function for overloaded 'RetsMetadata_GetAllTables'

### ISSUE THREAD

**Issue by ooglek** [NationalAssociationOfRealtors/libRETS#25]
When attempting to extend the RetsSession class in PHP, and attempting to call GetAllTables(), I ran into an issue where I got a Fatal error: No matching function for overloaded 'RetsMetadata_GetAllTables' when calling the method as 

```php
$this->GetAllTables($class);
```

as demonstrated in the php5/metadata.php example code file.

I was able to resolve it by changing my code to

```php
$this->getAllTables($resource, $class);
```

I'm not sure if this is a SWIG problem or a libRETS problem. The code generated in librets.php looks like this for me:

```php
function GetAllTables($metadataClass_or_resourceName,$className=null) {
    switch (func_num_args()) {
    case 1: $r=RetsMetadata_GetAllTables($this->_cPtr,$metadataClass_or_resourceName); break;
    default: $r=RetsMetadata_GetAllTables($this->_cPtr,$metadataClass_or_resourceName,$className);
    }
    if (is_resource($r)) {
        $c=substr(get_resource_type($r), (strpos(get_resource_type($r), '__') ? strpos(get_resource_type($r), '__') + 2 : 3));
        if (class_exists($c)) return new $c($r);
        return new MetadataTableList($r);
    }
    return $r;
}
```

I suspect the issue could be in the variable number of args passed, but I'm not really sure why passing it both parameters allows me to extend the class, but passing only the class does not.

**Comment by ooglek** [comment]
This [discussion in 2012 about Xapian](http://comments.gmane.org/gmane.comp.search.xapian.general/9346) is what led me define all possible arguments for GetAllTables in order to find my resolution.

**Comment by jazzklein** [comment]
Yeah, that might be a swig issue. In the librets.i file:

```
    MetadataTableList GetAllTables(MetadataClass * metadataClass) const;

    MetadataTableList GetAllTables(std::string resourceName,
        std::string className) const;
```
but I only see the function with the dual arguments. Use that API and you'll be OK - there isn't anything I can do about swig issues.
