### ISSUE TITLE
GetObject transaction appears to use wrong ID query parameter for RETS 1.8.0

### ISSUE THREAD

**Issue by MattMessmerBlossor** [NationalAssociationOfRealtors/libRETS#26]
I'm having trouble getting a RETS 1.8.0 GetObject transaction working. The server I'm connecting to expects the identifier query parameter to be called "ID", but libRETS is passing "Identifier" instead.

I found where this is happening here:
https://github.com/NationalAssociationOfRealtors/libRETS/blob/6914be0cbadb138deb8ec55b8432ebab556ca2c8/project/librets/src/GetObjectRequest.cpp#L126

I checked the RETS 1.8.0 specification and on page 38, under **5.3 Required Request Arguments**, it says "ID", which is what the server is looking for but isn't what libRETS is sending.

Can you clarify whether I've misinterpreted the spec or whether this is a bug? Thanks much! libRETS has been very helpful to me for a few months now.

**Comment by jazzklein** [comment]
Are we looking at the same spec? The one I have says "Identifier" (underlined) with "ID" struck out. The production I have is:
```
"Identifier"   UID | ID

UID ::= TOKEN *( "," TOKEN )
ID ::= resource-set *( "," resource-set)
resource-set ::= resource-entity [":" object-id-list ]
resource-entity ::= 1*ALPHANUM
object-id-list ::= "*" | object-id *( ":" object-id)
object-id ::= 1*5DIGIT```

**Comment by MattMessmerBlossor** [comment]
Haha, very interesting! I got my spec from:
http://www.reso.org/specifications/

I downloaded the first link, titled "RETS 1.8 Specification and DTD Document", which shows these lines under section 5.3:

```
ID UID | OBJECT_SET ; A string identifying the object or objects being
requested
UID ::= TOKEN *( "," TOKEN )
OBJECT_SET ::= resource-set *( "," resource-set)
resource-set ::= resource-entity [":" object-id-list ]
resource-entity ::= 1*ALPHANUM
object-id-list ::= "*" | object-id *( ":" object-id)
object-id ::= 1*5DIGIT
```

It's very possible I'm misunderstanding something, but then the server I'm trying to develop toward must also be missing the same thing. Thankfully the server also supports 1.7.2 so I'm using that in the meantime. Very strange! Can you confirm where you got your spec and see if I'm getting the wrong one somehow?

Thanks much for getting back to me!

**Comment by bwolven** [comment]
Some of the earlier RETS 1.8 documents had a new parameter "Identifier", but from what I understand it was causing too much confusion so they decided to using ID in the newer RETS 1.8 specification documents.

**Comment by jazzklein** [comment]
A quick scan of the RESO site seems to show me that 1.8.0a or 1.8.1a are both DRAFT state. At this point, I can only see the 1.8.0 spec as ratified. Can you please direct me to where the current ratified level is identified? Also, I've not been active in RESO for a while, so I'm a bit behind the curve here ... but, the dictionary for RETS-VERSION doesn't have a provision for a version number including an 'a'. So, at this point, I see of no way of telling the difference between the 1.8.0 version with "Identifier" and the 1.8.0a version with "ID".

**Comment by MattMessmerBlossor** [comment]
Very interesting. The only 1.8 spec I'm aware of is the one I linked to in my last post (not sure you saw my last). Here it is again:
http://www.reso.org/specifications/

Do you agree that that's the correct 1.8 spec? If so, unless I'm misreading something, it does show "ID" for that field. Weird that they would change the field name without incrementing the version number.

**Comment by jazzklein** [comment]
I checked the Confluence pages for the workgroup and that's where I see the various versions. So, evidently, the 1.8.0a document is what was finally released. What's interesting to me is that RESO funded the last round of changes to libRETS and the spec they provided me was the wrong one. And, this is the first time it's been discovered ... I take it no one else has a functional 1.8 server that libRETS has run against? Or do we face the possibility that some servers also implemented "Identifier" whereas others used "ID"? What's the error you saw from your server when "Identifer" was provided? Maybe we'll just add code to test both.

**Comment by bwolven** [comment]
Here is the link I was given that explained the reasoning behind keeping ID instead of Identity.

http://members.reso.org/display/RETS180a/5.3+Required+Request+Arguments

In Paragon RETS servers, for RETS 1.8, I check for both just to be safe because I thought it could be an issue since the specifications differed.
Another thing though is that a lot of users are still connecting as RETS 1.5 and 1.7.2, not 1.8 yet which could explain why it hasn't been much of an issue.

**Comment by MattMessmerBlossor** [comment]
Wow, weird! That is curious. Here's the server response I get when using "Identifier" instead of "ID" in a GetObject transaction:

```
<RETS ReplyCode="20401" ReplyText="Invalid Identifier"></RETS>
```

What's weird is that I don't think this code matches that message for the 1.8 spec. 20401 should be "Invalid Type". "Invalid Identifier" maps to 20402. So it's very possible this server has something iffy going on too. If it's important to libRETS, I can send them a support ticket and ask if there's any confusion over the spec on their end. Let me know.

Thanks a ton for your persistence on the problem!

**Comment by jazzklein** [comment]
Thanks ... that gives me a bit of history ... as I said .. I've not been active in Real Estate for a while and no one else seems to want to take over shepherding libRETS because of the Windows build hassle, so it I still do it when time permits. That means I'm always going to be _way_ behind the 8 ball!

I think I'll update libRETS to try both ID and Identifier as well - the latter only on an error on the former (I think .. I need to see if that fits into the nowait I/O architecture easily enough).

**Comment by MattMessmerBlossor** [comment]
Thanks for fixing this. When can I expect a release including this fix?

**Comment by MattMessmerBlossor** [comment]
Any chance of a new build with this fix? I'm running into issues with the server I mentioned and want to make sure it's not the fact that I'm using the wrong RETS version :) Thanks!

**Comment by jazzklein** [comment]
On Apr 25, 2016, at 9:15 AM, Matt Messmer <notifications@github.com> wrote:
> 
> Any chance of a new build with this fix? I'm running into issues with the server I mentioned and want to make sure it's not the fact that I'm using the wrong RETS version :) Thanks!


The fix is in trunk. If you’re asking for a Windows release … that’s going to take some time before I have time to attempt it again. Or are you just asking for the repo to be tagged?

**Comment by MattMessmerBlossor** [comment]
Looking for a Windows release on NuGet, yeah :/

**Comment by behm** [comment]
Mark,
Could you provide some documentation on how to build on Windows and I can see if I can setup a build process?  I have been publishing the Windows version to NuGet.  Not making any promises but I'd like to see what's involved and help out if I can.

Thanks,
Brian

**Comment by jazzklein** [comment]
On Apr 28, 2016, at 6:27 AM, Brian Behm <notifications@github.com> wrote:
> 
> Mark,
> Could you provide some documentation on how to build on Windows and I can see if I can setup a build process? I have been publishing the Windows version to NuGet. Not making any promises but I'd like to see what's involved and help out if I can.

ROTFL! OK, now that I have caught my breath ….

I need to preface this with “I’m not a Windows guy”. I originally stood up a Windows VM on Parallels in 2008 or so to do the Windows builds. I don’t recall everything I did to it to get it to work, because it was (painfully) iterative until I got it to work. It involved installing a bunch of MS developers kits and configuring separate Command windows for 32 and 64 bit builds. There were a bunch of support libraries that needed to get built that were part of the CRT subversion repo. I don’t see that they copied that over to GitHub and I can no longer connect to the original svn repo to see if they still exist there. They probably exist on that VM but I’ve got to go find the disk it’s on and spin it up to see. And, the last time I did that, there were about two days of Windows updates that needed to be applied, so I suspect that will be the case again.

I’m heading out of town for the next 10 days and just don’t have the time to look at this until I get back. Sorry.

**Comment by jazzklein** [comment]
On Apr 29, 2016, at 12:37 PM, Mark Klein <librets@dis.com> wrote:
> 
> On Apr 28, 2016, at 6:27 AM, Brian Behm <notifications@github.com> wrote:
>> 
>> Mark,
>> Could you provide some documentation on how to build on Windows and I can see if I can setup a build process? I have been publishing the Windows version to NuGet. Not making any promises but I'd like to see what's involved and help out if I can.
> 
> ROTFL! OK, now that I have caught my breath ….
> 
> I need to preface this with “I’m not a Windows guy”. I originally stood up a Windows VM on Parallels in 2008 or so to do the Windows builds. I don’t recall everything I did to it to get it to work, because it was (painfully) iterative until I got it to work. It involved installing a bunch of MS developers kits and configuring separate Command windows for 32 and 64 bit builds. There were a bunch of support libraries that needed to get built that were part of the CRT subversion repo. I don’t see that they copied that over to GitHub and I can no longer connect to the original svn repo to see if they still exist there. They probably exist on that VM but I’ve got to go find the disk it’s on and spin it up to see. And, the last time I did that, there were about two days of Windows updates that needed to be applied, so I suspect that will be the case again.
> 
> I’m heading out of town for the next 10 days and just don’t have the time to look at this until I get back. Sorry.

You’ll need to touch bases with Mark Lesswing at NAR to see if the subversion repo still exists and is publicly readable. The vendor and vendorsrc repos were not moved to github. If so, follow the instructions at http://code.crt.realtors.org/projects/librets/wiki/BuildWindows. I created those docs 6 years ago and they probably won’t work with current Windows distros but it will give you a start. I had a Makefile that builds most of the support stuff under cygwin, and a Makefile.vc that builds the Windows versions of libRETS. 

Good luck.

**Comment by mkhon** [comment]
4f95057bdf7d4ac9708b11df9ebd30de8b0a2616 also fixes unit tests for the Identifier -> ID fix

**Comment by mkhon** [comment]
@jazzklein I have a .bat file that builds all Windows librets (and ezrets) pre-requisites (for both x86 and x64)

- libcurl is built with WinSSL/SSPI (not OpenSSL) and without IDN

.bat file requires some manual operations (unpacking dist archives, applying a few patches for compilation fixes) but I think I can improve it so it does fully automated build.

I also wanted to consider a nuget build but haven't finished it (.bat file is much more usable now).
