### ISSUE TITLE
Zero results found but HTTP request has 141

### ISSUE THREAD

**Issue by dotcomly** [NationalAssociationOfRealtors/libRETS#27]
When I use librets to search for properties I get zero results however when I use my browser or the requests module I get 141 results. I know changes were made during the time frame provided so the 141 makes more sense and in fact includes the property I know had photos added. Other queries do get results so this seems to be an edge case but a very troubling one.

Here is a sample script which reproduces the problem:

```
import librets

rets_url = 'https://rets.crmls.org/contact/rets/login'
username = 'YOUR_USERNAME'
password = 'YOUR_PASSWORD'

# Fetch with librets
session = librets.RetsSession(rets_url)
session.Login(username, password)

request = session.CreateSearchRequest('Property', 'CrossProperty', '(TimestampModified=2016-04-22T15:31:00-2016-04-22T15:32:00)')
request.SetCountType(librets.SearchRequest.RECORD_COUNT_AND_RESULTS)
request.SetFormatType(librets.SearchRequest.COMPACT)

results = session.Search(request)

query = request.GetQueryString()

print 'LibRets Output:'
print '    Query: %s ' % query
print '    Count: %s' % results.GetCount() # 0
print '    Text: %s' % results.GetReplyText() # No Records Found
print '    HasNext: %s' % results.HasNext() # False
print ''

# Fetch without librets
import requests
from xml.etree import ElementTree
from requests.auth import HTTPDigestAuth

session_http = requests.get(rets_url, auth=HTTPDigestAuth(username, password))

# Use the exact query returned from librets
url = 'https://rets.crmls.org/contact/rets/search?%s' % query

data = requests.get(url, cookies=session_http.cookies).text
response = ElementTree.fromstring(data)

print 'HTTP Output:'
print '    Count: %s' % response.find('COUNT').get('Records') # 141
```
- Note that the count will go down over time as properties are modified again

**Comment by dotcomly** [comment]
Returned records are now down to 97. Can someone verify this bug before all 141 properties are modified and you mark it as not reproducible?

**Comment by jazzklein** [comment]
I can't duplicate what you're seeing. Turn on tracing and capture the logs. Zip them up and send them to me. I’ll look at them when I get back into town.

**Comment by dotcomly** [comment]
I could not find any documentation about tracing or references to trace in the source code. I did find some logging related code and it did produce an HTTP log which I will send privately to github@dis.com.

A few questions...
In your efforts to reproduce, did my sample script run?
How many results did you get from librets. How many from requests?
Did you use CRMLS credentials for their production system?

This is the code I added to my sample script to get the log:

    session = librets.RetsSession(rets_url)
    + session.SetHttpLogName('/var/log/librets.log')
    + session.SetLogEverything(True)
    session.Login(username, password)

As you will see it returns `<RETS ReplyCode="20201" ReplyText="No Records Found" />` however if you go to `https://rets.crmls.org/contact/rets/login` then `https://rets.crmls.org/contact/rets/search?Class=CrossProperty&Count=1&Format=COMPACT&Query=%28TimestampModified%3d2016-04-22T15:31:00-2016-04-22T15:32:00%29&QueryType=DMQL2&SearchType=Property&StandardNames=0` you will get 89 results.

**Comment by jazzklein** [comment]
Sorry, I don't have your credentials. I simply tried to duplicate a time based request to my server which worked. The logs indicate that libRETS did post your query properly to the server and got the 20201 back. 

```
POST /contact/rets/search HTTP/1.1
Authorization: Digest username="*REDACTED*", realm="*REDACTED*", nonce="*REDACTED*", uri="/contact/rets/search", cnonce=
"*REDACTED*", nc=00000003, qop=auth, response="*REDACTED*", opaque="*REDACTED*"
Host: rets.crmls.org
Accept: */*
Cookie: RETS-Session-ID=*REDACTED*; JSESSIONID=*REDACTED*
RETS-Version: RETS/1.5
User-Agent: librets/1.6.1
X-Librets-Version: 1.6.1, libCURL - libcurl/7.29.0 NSS/3.19.1 Basic ECC zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Content-Length: 162
Content-Type: application/x-www-form-urlencoded

Class=CrossProperty&Count=1&Format=COMPACT&Query=(TimestampModified%3d2016-04-22T15:31:00-2016-04-22T15:32:00)&QueryType=DMQL2&SearchType=Property&StandardNames=0* upload completely sent off: 162 out of 162 bytes

<<< Received
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
* Replaced cookie JSESSIONID="*REDACTED*" for domain rets.crmls.org, path /contact, expire 0

<<< Received
Set-Cookie: JSESSIONID=*REDACTED*; Path=/contact
MIME-Version: 1.0
Cache-Control: private
RETS-Version: RETS/1.5
Content-Type: text/xml
Content-Length: 57
Date: Fri, 29 Apr 2016 20:02:43 GMT

<RETS ReplyCode="20201" ReplyText="No Records Found" />
```

You're going to need to get the server guys to tell you why the query works as a GET but fails as a POST. The RETS spec allows for either a GET or POST and because search criteria can exceed length limits, we always do a POST.

**Comment by dotcomly** [comment]
It seems post requests to their server does return the expected results. Do you not have access to CRMLS system? I can contact them and see if they can give you some temp ones to debug this. I usually get results with similar queries and only noticed this because someone complained a property did not update so this is certainly a difficult edge case. 

Here is a test HTML file that posts data to their server. You will need to manually go to the login url `https://rets.crmls.org/contact/rets/login` before submitting the forms.

    <html>
        <head>
            <title>This Is A Test</title>
        </head>
        <body>
            <h2>Test with fielded values (works)</h2>
            <form method="post" action="https://rets.crmls.org/contact/rets/search">
                <input type="text" name="Class" value="CrossProperty">
                <input type="text" name="Count" value="1">
                <input type="text" name="Format" value="COMPACT">
                <input type="text" name="Query" value="(TimestampModified=2016-04-22T15:31:00-2016-04-22T15:32:00)">
                <input type="text" name="QueryType" value="DMQL2">
                <input type="text" name="SearchType" value="Property">
                <input type="text" name="StandardNames" value="0">
                <input type="submit">
            </form>
            <br/><br/>
            <h2>Test with url values (works)</h2>
            <form method="post" action="https://rets.crmls.org/contact/rets/search?Class=CrossProperty&Count=1&Format=COMPACT&Query=%28TimestampModified%3d2016-04-22T15:31:00-2016-04-22T15:32:00%29&QueryType=DMQL2&SearchType=Property&StandardNames=0">
                <input type="submit">
            </form>
            <br/><br/>
            <h2>Test with url values not url encoded (works)</h2>
            <form method="post" action="https://rets.crmls.org/contact/rets/search?Class=CrossProperty&Count=1&Format=COMPACT&Query=(TimestampModified=2016-04-22T15:31:00-2016-04-22T15:32:00)&QueryType=DMQL2&SearchType=Property&StandardNames=0">
                <input type="submit">
            </form>
        </body>
    </html>
