### ISSUE TITLE
Add ability to AddAllObjects starting at specific index

### ISSUE THREAD

**Issue by MattMessmerBlossor** [NationalAssociationOfRealtors/libRETS#28]
This is sort of a weird use case, but the RETS server I'm building toward serves up the same image for index 0 and index 1. I'd like to `AddAllObjects` starting at index 1 so that I don't waste time downloading the 0th image.

Right now I'm working around this by not calling `GetDataAsBytes` on the first result, but this is confusing (trying to reuse code across many RETS servers and this is an exception) and it'd be a lot cleaner to start at a specific index.

If there's a way I can already accomplish this, please let me know. Thanks!

**Comment by dmbware** [comment]
Did you ever find a solution to your problem ?

**Comment by MattMessmerBlossor** [comment]
Just the workaround that I mentioned above. It's been a long time since I've worked on this code so my memory is foggy, but I don't think I found a better solution.

**Comment by dmbware** [comment]
By chance have you seen this error when pulling down photos ? 

<RETS ReplyCode="20409" ReplyText="Object Unavailable [170050779:1]." >
</RETS>

Our code uses GetObject to pull the photos from Sandicor. We do so sequentially, based on the number of photos your system tells us that are available. We use the AddAllObjects method to the GetObjectRequest to query RETS for a list of all possible objects of the type defined, then iterate over them.

**Comment by MattMessmerBlossor** [comment]
I don't recall any errors related to the issue, but I'm not entirely sure what error you're referring to. This issue was just for optimization on my end...I don't think there were any problems I ran into other than a lack of functionality.
