### ISSUE TITLE
no type named 'streamsize' in namespace 'std'

### ISSUE THREAD

**Issue by zzeng4** [NationalAssociationOfRealtors/libRETS#29]
g++ -g -O2 -DHAVE_CONFIG_H -fPIC `/Users/Ubene/Documents/librets/client/libRETS/librets-config-inplace --cflags` -I./project/librets/include -Ibuild/swig/csharp -I/Users/Ubene/Documents/librets/client/libRETS/project/swig/csharp -I/Users/Ubene/Documents/librets/client/libRETS/project/swig -c build/swig/csharp/librets_wrap.cpp -o build/swig/csharp/librets_wrap.o
In file included from build/swig/csharp/librets_wrap.cpp:417:
/Users/Ubene/Documents/librets/client/libRETS/project/swig/librets_bridge.h:58:72: error: no type named 'streamsize' in namespace 'std'
    std::size_t write(unsigned char buffer[], std::size_t offset, std::streamsize length) const;
                                                                  ~~~~~^
1 error generated.
make[1]: **\* [build/swig/csharp/librets_wrap.o] Error 1

What happened here> anyone knows?

**Comment by jazzklein** [comment]
On May 16, 2016, at 2:01 PM, zzeng4 <notifications@github.com> wrote:
> 
> g++ -g -O2 -DHAVE_CONFIG_H -fPIC /Users/Ubene/Documents/librets/client/libRETS/librets-config-inplace --cflags -I./project/librets/include -Ibuild/swig/csharp -I/Users/Ubene/Documents/librets/client/libRETS/project/swig/csharp -I/Users/Ubene/Documents/librets/client/libRETS/project/swig -c build/swig/csharp/librets_wrap.cpp -o build/swig/csharp/librets_wrap.o
> In file included from build/swig/csharp/librets_wrap.cpp:417:
> /Users/Ubene/Documents/librets/client/libRETS/project/swig/librets_bridge.h:58:72: error: no type named 'streamsize' in namespace 'std'
> std::size_t write(unsigned char buffer[], std::size_t offset, std::streamsize length) const;
> ~~~~~^
> 1 error generated.
> make[1]: *** [build/swig/csharp/librets_wrap.o] Error 1
> 
> What happened here> anyone knows?

Tell me more about your build platform. Operating system, gcc/g++ version, etc. There apparently are some versions of the gnu libraries that have mucked up <iosfwd>. You can try changing the line with <iosfwd> in include/librets/std_forward.h to <ios> and see if that helps.

**Comment by jazzklein** [comment]
On May 18, 2016, at 8:13 AM, Mark Klein <librets@dis.com> wrote:


> You can try changing the line with <iosfwd> in include/librets/std_forward.h to <ios> and see if that helps.

On second thought .. scratch that. That’s going to defeat the purpose of using the forward declarations elsewhere.

In librets_bridge.h, after the line #include "librets/std_forward.h”, add #include <ios>

**Comment by zzeng4** [comment]
@jazzklein 

Thanks for reply

I have figure it out, and it compiled successfully with python binding.

**Comment by zetlan** [comment]
@zzeng4 great that you figured it out, could you post a solution? I'm having this exact problem.

**Comment by raiprabh** [comment]
hey @zetlan I found the same issue. I solved it by adding `#include <ios>` in the `project/swig/librets_bridge.h`, to include `streamsize`. Then there was another issue regarding building in `.NET`, something related to typemap error `IntPtr`. I disabled that in `./configure` since I was not using it. That's again another issue that users might be facing.

**Comment by zetlan** [comment]
I solved this problem by abandoning librets entirely and going with a different solution, since this one doesn't seem to see much maintenance.

**Comment by marwanhaddad** [comment]
Zeltan, what other option did you use? thanks for your help
