### ISSUE TITLE
libRETS unresolved symbols

### ISSUE THREAD

**Issue by lance0821** [NationalAssociationOfRealtors/libRETS#31]
I am trying to us the C++ includes in a Visual Studio 2015 project, I have downloaded Boost 1.60, unzipped to C:\boost_160, and ran to the b2 commands to populate staging/libs, in visual studio I have added the librets include directory in additional includes under c/c++ and I have added the boost/staging/libs directory under Linker additional library directories, but when I try a simple login log off command, I get an error like this 
Severity    Code    Description Project File    Line    Suppression State
Error   LNK2019 unresolved external symbol "public: bool __cdecl librets::RetsSession::Login(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?Login@RetsSession@librets@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z) referenced in function main    RETSTest    C:\Users\Lance\Documents\Visual Studio 2015\Projects\RETSTest\RETSTest\main.obj 1

Any help would be appreciated to getting this to compile

**Comment by jazzklein** [comment]
Sorry, I'm not a Windows guy. I'd suggest you try talking to https://github.com/mkhon since he's been providing updates for the Windows build and therefore must be building it.
