### ISSUE TITLE
Running on Azure Functions

### ISSUE THREAD

**Issue by josephbisaillon** [NationalAssociationOfRealtors/libRETS#32]
I'm having an issue getting this to work on azure functions. I keep getting `The type initializer for 'librets.libretsPINVOKE' threw an exception.`

I have both the 32Bit and 64Bit dll's provided on nuget 1.6.2, does anyone have a solution for this?

**Comment by behm** [comment]
Were you able to get this working?

**Comment by josephbisaillon** [comment]
@behm I was able to solve the issue. Using the default project.json to have nuget download the libraries had it downloaded into a location that the function couldn't find. I just manually moved the library to correct location and that allowed it to work. I'll close out this issue.
