### ISSUE TITLE
Multi-threaded implementation is blocking on requests

### ISSUE THREAD

**Issue by pebrmatt** [NationalAssociationOfRealtors/libRETS#52]
I'm pulling data from multiple MLSs and have recently updated my Python app to handle each MLS in a separate thread. Some of the MLSs can be very sluggish, so I was hoping to speed things up by doing each MLS in parallel. The problem I've run into is that once any thread has initiated a RETS Search request (or GetObject request), no other thread can start a request until the first thread's request has returned. 

I understand not wanting to send simultaneous requests to a single MLS, but these are independent MLSs, so I'm only trying to send a single request to any given MLS at at time.

Is there a way to avoid the blocking for requests on a different thread? Or is there a better way to 
handle this situation?

Thanks,
Matt

**Comment by jazzklein** [comment]
Did you build libRETS with threading enabled? Even with that, I suspect you are still going to have problems. libRETS is native C++ and you are running it in what is essentially a separate VM. Python's VM threading may not work well with pthreads running in a separate context. I don't remember all the SWIG complexities for invoking native code from the VM, and I'm sure there is stuff happening there, too.

**Comment by pebrmatt** [comment]
Yes, it was built wth threading enabled — but it looked like the session info was still being treated as a global.

We wound up switching over to multi-processing (still with Python), and that’s working fine. Some of the RETS platforms don’t allow multiple simultaneous requests from the same IP address (even if they’re for different MLSs), so requests going to the same platform have to be queued up. Getting that working dropped our conversion time on about 70 MLSs from about 2.5 hours down to about 1/2 an hour.

Thanks,
Matt

**Comment by jazzklein** [comment]
Yeah, many MLSs do that to avoid performance issues, especially when someone tries to take a full dump of all the data. As for multi-processing instead of multi-threading .. that's your best bet. As I said, I'm really not sure how Python multithreading would play when escaping to `libRETS`.
