### ISSUE TITLE
Bad code in Section 5.3

### ISSUE THREAD

**Issue by dwats2016** [NationalAssociationOfRealtors/libRETS#56]
You'll see it near the C# section. Seems like it was supposed to be it's own section like the other languages have. Just wanted to help. Thanks!

Link where the bug is found:
	https://github.com/NationalAssociationOfRealtors/libRETS/wiki/Developer's-Guide#getobject-fetch

</pre><p>
    **In C#, we will demonstrate two ways to fetch the data:**
</p><div class="itemizedlist"><ul class="itemizedlist" type="disc"><li class="listitem">
    Using the C++ iostream;
</li><li class="listitem">
    Fetch the data as a series of bytes and using a helper class called 
    <code class="literal">BinaryWriter</code> to write the data.
</li></ul></div><pre class="programlisting">// C#
    GetObjectResponse response = session.GetObject(request);

**Comment by jazzklein** [comment]
Fixed formatting.
