### ISSUE TITLE
node-gyp not building the librets directory

### ISSUE THREAD

**Issue by AbrahamFergie** [NationalAssociationOfRealtors/libRETS#57]
I am running on a debian linux system and am trying to build the node.js version but I keep getting this back:
![screenshot 2017-12-06 at 10 38 56 am](https://user-images.githubusercontent.com/15825329/33683788-f3bfa832-da80-11e7-8766-d16d9c8c1a78.png)
Any help would be greatly appreciated.

**Comment by whk-io** [comment]
Have you tried with Node 10?
