### ISSUE TITLE
build faild

### ISSUE THREAD

**Issue by nyousefzai** [NationalAssociationOfRealtors/libRETS#58]
Navid-Devs-MacBook-Pro:libRETS navid_dev$ build
-bash: build: command not found
Navid-Devs-MacBook-Pro:libRETS navid_dev$ make 
antlr -o build/librets/antlr ./project/librets/src/rets-sql.g
ANTLR Parser Generator   Version 2.7.7 (20171210)   1989-2005
antlr -o build/librets/antlr -glib ./project/librets/src/rets-sql.g ./project/librets/src/dmql-tree.g
ANTLR Parser Generator   Version 2.7.7 (20171210)   1989-2005
antlr -o build/librets/antlr -glib ./project/librets/src/rets-sql.g ./project/librets/src/get-object-tree.g
ANTLR Parser Generator   Version 2.7.7 (20171210)   1989-2005
antlr -o build/librets/antlr -glib ./project/librets/src/rets-sql.g ./project/librets/src/lookup-tree.g
ANTLR Parser Generator   Version 2.7.7 (20171210)   1989-2005
antlr -o build/librets/antlr -glib ./project/librets/src/rets-sql.g ./project/librets/src/lookup-columns-tree.g
ANTLR Parser Generator   Version 2.7.7 (20171210)   1989-2005
touch build/librets/antlr/.antlr-up-to-date
g++ -g -O2 -fPIC -DHAVE_CONFIG_H  -DTARGET_UNIX -DLIBRETS_VERSION='"1.6.3-SNAPSHOT"' -I/usr/local/include  -I./project/librets/include -c build/librets/antlr/RetsSqlLexer.cpp -o build/librets/antlr/RetsSqlLexer.o
In file included from build/librets/antlr/RetsSqlLexer.cpp:2:
build/librets/antlr/RetsSqlLexer.hpp:4:10: fatal error: 'antlr/config.hpp' file not found
#include <antlr/config.hpp>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [build/librets/antlr/RetsSqlLexer.o] Error 1
make: *** [all] Error 2
Navid-Devs-MacBook-Pro:libRETS navid_dev$ 

Thanks in advance for any help

**Comment by jazzklein** [comment]
Are you using Macports or Brew? How did you configure? Use `librets-build.sh` if you just manually did it. You need to include the CPPFLAGS to work properly:
```
CPPFLAGS="-L/opt/local/lib -I/opt/local/include"   ./configure  .....
```

**Comment by nyousefzai** [comment]
Thanks for your response, i have used MacPorts  now i am stack in here ..
---------------------------------------------------------------------------------------------

Compile SWIG bindings.......: yes
  With DotNet...............: no
  With Java.................: no
  With PERL.................: yes
  With PHP..................: yes
  With Python 2.............: yes
  With Python 3.............: no
  With Ruby.................: no
  With Node.js..............: yes
Enable Maintainer Docs......: no
Enable Universal Objects....: no

Navid-Devs-MacBook-Pro:libRETS navid_dev$ make
swig -c++ -perl -o build/swig/perl/librets_wrap.cpp \
	-outdir build/swig/perl /Users/navid_dev/Desktop/test/libRETS/project/swig/librets.i
:3: Error: Unable to find 'perl5.swg'
/Users/navid_dev/Desktop/test/libRETS/project/swig/librets.i:86: Error: Unable to find 'std_string.i'
/Users/navid_dev/Desktop/test/libRETS/project/swig/librets.i:88: Error: Unable to find 'std_vector.i'
make[1]: *** [build/swig/perl/librets_wrap.cpp] Error 1
make: *** [all] Error 2
Navid-Devs-MacBook-Pro:libRETS navid_dev$

**Comment by nyousefzai** [comment]
with my configure i disabled perl and php now i get this 

Enable Maintainer Docs......: no
Enable Universal Objects....: no

Navid-Devs-MacBook-Pro:libRETS navid_dev$ make
cd build/swig/python ; \
	CC="gcc" CXX="g++" CFLAGS="-g -O2 -fPIC -DHAVE_CONFIG_H" CXXFLAGS="-g -O2 -fPIC -DHAVE_CONFIG_H" \
	python setup.py build  
sys.platform: darwin
running build
running build_py
running build_ext
cp /Users/navid_dev/Desktop/test/libRETS/project/swig/node.js/binding.gyp build/swig/node.js
swig -c++ -javascript -node -DV8_VERSION=0x0601534 \
	-o build/swig/node.js/librets_wrap.cpp -outdir build/swig/node.js /Users/navid_dev/Desktop/test/libRETS/project/swig/librets.i
:3: Error: Unable to find 'javascript.swg'
/Users/navid_dev/Desktop/test/libRETS/project/swig/librets.i:86: Error: Unable to find 'std_string.i'
/Users/navid_dev/Desktop/test/libRETS/project/swig/librets.i:88: Error: Unable to find 'std_vector.i'
make[1]: *** [build/swig/node.js/librets_wrap.cpp] Error 1
make: *** [all] Error 2
Navid-Devs-MacBook-Pro:libRETS navid_dev$

**Comment by jazzklein** [comment]
`SWIG` also needs the various language ports installed.

```  swig @3.0.12_0 (active)
  swig-csharp @3.0.12_0 (active)
  swig-java @3.0.12_0 (active)
  swig-perl @3.0.12_0 (active)
  swig-python @3.0.12_0 (active)
  swig-ruby @3.0.12_1+ruby23 (active)
```

**Comment by nyousefzai** [comment]
Thanks Mr. klein , i have spend all day trying to make this on mac , i was able to make it on Linux but no luck on mac so fare  is there any updated doc on build with mac ?  i am stack here , but i think its the same issue ----------------------------------------------------------------------------------------------------
Navid-Devs-MacBook-Pro:libRETS navid_dev$ make
g++ -g -O2 -fPIC -DHAVE_CONFIG_H -fPIC `/Users/navid_dev/libRETS/librets-config-inplace --cflags` -I./project/librets/include -Ibuild/swig/csharp -I/Users/navid_dev/libRETS/project/swig/csharp -I/Users/navid_dev/libRETS/project/swig -c build/swig/csharp/librets_wrap.cpp -o build/swig/csharp/librets_wrap.o
In file included from build/swig/csharp/librets_wrap.cpp:419:
/Users/navid_dev/libRETS/project/swig/librets_bridge.h:58:72: error: no type
      named 'streamsize' in namespace 'std'
  ...write(unsigned char buffer[], std::size_t offset, std::streamsize length...
                                                       ~~~~~^
1 error generated.
make[1]: *** [build/swig/csharp/librets_wrap.o] Error 1
make: *** [all] Error 2
Navid-Devs-MacBook-Pro:libRETS navid_dev$

**Comment by jazzklein** [comment]
Unfortunately, I've not really worked on any of this in over 5 years. In that time, NAR decomissioned the subversion server and the CRT wiki server. And OS X has been updated quite a bit since `Snow Leopard`.

Mind you, `boost` changes quite a bit between revisions, and there have been breaking changes that did affect `libRETS` in the past. This is the version I have installed:

```
  boost @1.59.0_3+no_single+python27 (active)
```
I'm guessing that may be part of it. 

Nonetheless, you are building this on a Mac. Why are you trying to build `C#`? What is your final goal?

**Comment by nyousefzai** [comment]
we are experimenting some options for a system to deal with many rets server.  i am going to close this issue, as it has been addressed. 
i am able to build in linux  " node " version of librets .

Thanks for your help,  if you have any suggestion that can help my startup that would be super nice please contact me : navid  _ kan @ yahoo   . com       
CEO @  Zoopify inc .
