### ISSUE TITLE
Like to report broken link in the Build Windows Help section

### ISSUE THREAD

**Issue by dsscsystems** [NationalAssociationOfRealtors/libRETS#59]
hello, i would like to report broken links to the vs 2003-2008 source code, for compile sources using visual studio, here is the link, https://github.com/NationalAssociationOfRealtors/libRETS/wiki/Building-on-Windows.

look like crt.realtor.org, is no a redirect so any prior link that use to work no work, when i try to us SNV to check out source for any of thos location in the build windows help description.

**Comment by jazzklein** [comment]
I'm not sure much can be done about that - the old servers are gone to my knowledge.
