### ISSUE TITLE
abundance of 404 Connection Errors when attmepting to connect to rets server...

### ISSUE THREAD

**Issue by robdob** [NationalAssociationOfRealtors/libRETS#60]
when using librets.dotnet V4.0.30319 ( from Nuget Package 1.6.2 )  I seem to be encountering a lot of 404 connection errors.  I have spoken to the rets server people and they tell me that they have no record of any connection problems.  They seem to think its all on my end..  Prior I don't think that I was ever getting any errors on connection.  I'm not sure if it related to the latest librets or not..  
this error I'm getting is:

Could not get URL [ http://rets.torontomls.net:6103/rets-treb3pv/server/action] - HTTP response code: 401 

Any help would be greatly appreciated..
thanks in advance..

**Comment by robdob** [comment]
I've gone back to using V1.5.2 and everything seems much better so the last two releases of librets don't seem to be that stable for me..  Do you have plans to address this and release a stable version or am I best to stay with this oldest version?

thanks,

**Comment by zBestData** [comment]
I believe we are experiencing the same or similar problem.  On March 28, 2017 we lost the ability to connect with NavicaMLS and have been receiving this error.

_

_Could not get URL [ https://rets2.navicamls.net/login.aspx] - HTTP response code: 503 Service Unavailable_

_

We are able to connect via other methods, phpRETS and RetsConnector, but not via the libRets.dll.  So far, we have only seen the issue with Navica.  None of the other RETS providers.  So far we have not been able to resolve the problem and rolling back the version has had no effect.

**Comment by RobOverman** [comment]
I am connecting to a Matrix (CoreLogic) RETS server with v4.0.30319 without any issue. Could it be a default RETS version issue? That is, setting session.SetRetsVersion(librets.RetsVersion) to a lower version. I don't have access to Navica or Stratus servers so this is just a guess.

**Comment by zBestData** [comment]
Already tried rolling back the version.   Event made a bare bones test app that was tried on 4 different machines using 3 different networks.  No luck.  Can connect to Matrix, Flex, reDataVault, and a couple MLS's with their own independent server.  Just not Navica.

**Comment by rpratt7opals** [comment]
In my case 503 Service Unavailable error turned out to be a TLS 1.2 issue. I just had a server move from http to https (Matrix). And when it did, I went 503.
It doesn't look like librets supports TLS 1.2 (see Issue #21), at least for Windows. I solved my problem for now by using the MODE_NO_SSL_VERIFY flag on the RETSSession to disable verification of the certificate.
session.SetModeFlags(RETSSession.MODE_NO_SSL_VERIFY);
See //groups.google.com/forum/#!msg/librets/MHmQvcqudLI/wRTYjQlIAwAJ
If anyone knows of a TLS 1.2 solution for librets, please let me know.

**Comment by faithlynnsteltzer** [comment]
@zBestData I realize it's been a long time, but did you ever get resolution on connecting to Navica? I am having this exact problem right now with my company's proprietary RETS software and I've come to libRETS hoping to troubleshoot/compare to our software and get the same 503 error on login. Any help you can offer is greatly appreciated!

**Comment by zBestData** [comment]
Yes!  Thank you for following up!

The solution that finally worked for us was setting the “RETS Mode” to MODE_NO_SSL_VERIFY. Apparently, there has been an update somewhere that has not gotten to everyone.  Navica seemed pretty oblivious and wasn’t much help in identifying possible causes or changes in the system.  I was pretty much on own in trying to figure out a solution to the problem.   Our platform is also proprietary and built on the libRETS.dll provided by RESO.  Feel free to reach out to me directly if you want to compare notes.  I am in North Carolina on Eastern Standard Time and am usually free most days between 10am and 2pm.

All the Best!

Graham Davis
zBest Data Technologies, LLC
Durham, NC
(919) 251-5050
zBestData.com<http://zbestdata.com/>
Microsoft Partner

[Untitled-1]
Make it simple ∙ Make it easy  ∙ Make it flow!

**Comment by jbramleycl** [comment]
The latest changes to the windows build allow for it to compile against a newer version of openssl and thus support TLS1.2.
