### ISSUE TITLE
Connection to https server fails

### ISSUE THREAD

**Issue by damonjanis** [NationalAssociationOfRealtors/libRETS#61]
One of the MLSs we connect to changed their URL from non-secured http://matrixrets.ntreis.net/rets/login.ashx to secured https://matrixrets.ntreis.net/rets/login.ashx

Now when calling Session.Login(userName, password) an exception is thrown:

"Could not get URL [ https://matrixrets.ntreis.net/rets/login.ashx] - HTTP response code: 503"

I've tried versions 1.5.2, 1.6.1, and 1.6.2 of the libret-dotnet library and they all have the same result.

Is there something that needs to be set or called to connect to an https server?

**Comment by behm** [comment]
Have you tried this:
retsSession.SetModeFlags(RetsSession.MODE_NO_SSL_VERIFY);

See this post: https://groups.google.com/forum/#!searchin/librets/ssl%7Csort:relevance/librets/g62O8pxsAcg/AXzlKi133TUJ

**Comment by damonjanis** [comment]
Yes that solved the problem. Thank you!
