### ISSUE TITLE
query.GetColumns() returns empty tuple

### ISSUE THREAD

**Issue by giovannirescia** [NationalAssociationOfRealtors/libRETS#62]
Hi all, am using libRETS for the first time, and used the Developer's Guide as a tutorial, the problem is that I can't get the columns from the queries, for example:
```
req = session.CreateSearchRequest("Property", "CMF", "(YearBuilt=1+) , (ListingStatus=|1,2)")
res = session.Search(req)
```
`res.GetCount()` yields 438 hits, but `res.GetColumns()` returns an empty tuple, what am I missing?

I am using the Python binding for this.

Thanks,
Giovanni

**Comment by nyousefzai** [comment]
I think the issue is with your query.
not that familiar with python but you can try 

req = session.CreateSearchRequest("Property", "CMF", "(YearBuilt=2018-")

you can create different search query based on your feed class and tables.

**Comment by giovannirescia** [comment]
@nyousefzai That didn't do trick either, I also tried different queries and classes.

**Comment by nyousefzai** [comment]
are you able to get metadata?

**Comment by giovannirescia** [comment]
Yes, I can get the metadata. Finally I solved this problem with the following line `req.SetFormatType(librets.SearchRequest.COMPACT_DECODED)`.

**Comment by Valachio** [comment]
@giovannirescia Thanks for posting that solution.  Saved me hours of figuring out a solution.

Quick question for you - are the 'Date' fields looking weird for you?  My date fields are coming out in this format: XX:XX.0 and it doesn't seem to include the date.

**Comment by giovannirescia** [comment]
@Valachio I switched to https://github.com/opendoor-labs/rets which is easier to use, hope it helps you!

**Comment by Valachio** [comment]
@giovannirescia Thanks for that link.  For whatever reason I cannot seem to login with opendoor's rets client.  Going have to figure out this date issue with librets...
