### ISSUE TITLE
Documentation links down

### ISSUE THREAD

**Issue by ateymour** [NationalAssociationOfRealtors/libRETS#65]
I noticed the same thing was reported for windows links and I understand the servers are down.
But Im wondering is there any alternative locations I can access API documentations? Seems like there is currently no resources for help if something goes wrong.
Any sort of minute API documentation would be very helpful

**Comment by jazzklein** [comment]
I have an older version up on my site. Feel free to use it: ```https://www.dis.com/NAR/api/user/```. Ignore the warning about insecure site ... I've self signed my own certs.

Beyond that, the servers at NAR are out of my reach these days and would take someone there to fix those issues. I've assigned this to Chad to see if he can help.
