### ISSUE TITLE
Time to Release 1.6.3 Maybe?

### ISSUE THREAD

**Issue by ooglek** [NationalAssociationOfRealtors/libRETS#67]
It looks like the `NEWS` was updated over a year ago with improvements such as 1.8 GetObject improvements. 

Any chance a new release is forthcoming?

Also, the `README.md` for this project seems to have gotten updated with some `libRETS Docker` info, which seems strange and wrong.

**Comment by jazzklein** [comment]
Are you looking for a Windows release? If so, that probably won't happen unless someone with better Windows experience than I can rebuild this. If not, keep in mind you can always build from HEAD and get what would be in 1.6.3. I'll try to do a release when I get some time free.

**Comment by kjaleshire** [comment]
Is it possible to include a .NET Core target in the next release?

**Comment by abidCharlotte49er** [comment]
Is this project actively maintained? I'm trying to add Librets library in .Net Core project, I have tried all these 3 packages in nuget and none of them worked https://www.nuget.org/packages?q=librets it says current library is unsupported or I get "The type initializer for 'librets.libretsPINVOKE' threw an exception." I'm working on a project to connect to MLS from Amazon AWS over Lambda and can't use current Librets libraries. Is there source code for .NET ?

**Comment by jazzklein** [comment]
It is only being maintained by individual contributors these days. And it is not at .NET application ... it is Linux based, but uses a wrapper to mostly make it work on Windows. That said ... there is someone with updates to the Windows version that we're trying to get merged.

**Comment by kjaleshire** [comment]
@abidCharlotte49er You must copy `\libRETS-x64\1.6.2\lib\native\librets-pinvoke.dll` to your application folder. Because the NuGet package is a wrapped native library, you're restricted to running in Windows.

I stopped using it this weekend in fact. It was easy enough to re-implement directly in C# with `HttpClient`, `SocketsHttpHandler`, and an XML parser.

**Comment by abidCharlotte49er** [comment]
@kjaleshire @jazzklein Thank for both for your advice, honestly didn't expect you guys would respond so quickly. Really appreciate you guys taking time and responding. 
I have added librets-pinvoke.dll in my application and I could now get RetsSession, hopefully this is all I need to do to make this work. 

On a side note I see someone posted beta1 last night but there is no release notes. I wonder what's in it ?

https://www.nuget.org/packages/libRETS-x64/1.6.3-beta1

**Comment by abidCharlotte49er** [comment]
Ran into another problem. AWS ignores pinvoke.dll. I tried adding that library as reference. I get "Invalid or unsupported" error. I can manually copy that file in my project but AWS ignores this file since it is not added in the project files. I have added below item in the csproj and that didn't help either. Why can't pinvoke part of the Nuget package? Any other workaround to add this library as part of project file ? 
  
`  <ItemGroup>
    <Reference Include="librets-pinvoke">
      <HintPath>bin\Release\netcoreapp2.1\librets-pinvoke.dll</HintPath>
    </Reference>	
  </ItemGroup>`

**Comment by jazzklein** [comment]
Sorry, I'm not a Windows guy and maybe one of them will speak up. But, I do remember that there were somethings about security issues surrounding `signed objects in the cache` if that means anything to you. You may need to self sign things if your target machine is running at a higher security level. Hope that helps. Otherwise, you'll need to wait for a Windows guy to respond.

**Comment by behm** [comment]
The v1.6.3-beta1 NuGet package includes the updates created by @jbramleycl in PR #72.  I am not sure how/when an official 1.6.3 release would be created so I named it 1.6.3 to increase the NuGet package version.  I have started work on a .NET Standard version of a RETS library but it's been slow going. Maybe @kjaleshire has the best approach for .NET Core support.

**Comment by abidCharlotte49er** [comment]
Thanks Brian,  Please keep us, Windows guys posted when we have an update on that.

**Comment by jazzklein** [comment]
1.6.3 Released.

**Comment by kjaleshire** [comment]
What I have is nowhere a complete implementation. It's only able to login, do resource searches, and de-serialize the results back. But if this interests anyone I'm fine spending some time extracting what I have and open-sourcing it.

**Comment by abidCharlotte49er** [comment]
Mark, 

Is there a complete release notes for 1.6.3 ? 

Kyle,

Can you please send what you have ? I’ll review and see if I can contribute.  

Thanks

**Comment by jazzklein** [comment]
Unfortunately, the release notes are not complete as there were a bunch of pull requests over the past few years that didn't include updates. You're best bet is to review the git log.

**Comment by kjaleshire** [comment]
Sure, I'll try to find some time this weekend to post it and let you know.

**Comment by kjaleshire** [comment]
@abidCharlotte49er I've posted my client code at https://github.com/kjaleshire/RetsExchange.

**Comment by abidCharlotte49er** [comment]
@kjaleshire Thank You I will review when I get a chance. I manged to host my .NET Core application on windows server working with LibRETS 1.6.3 release. I had to add references manually. It won't work when I install LibRets from Nuget PM. I also have to change something in the build properties to work. Adding those screenshots for .NET developers for reference. Thanks 

![image](https://user-images.githubusercontent.com/2357276/56595669-0fcf9f00-65bd-11e9-9584-a7894c235fae.png)

![image](https://user-images.githubusercontent.com/2357276/56595425-9f288280-65bc-11e9-989a-b4c282ada8ca.png)

**Comment by abusalaa7** [comment]
@abidCharlotte49er  can you share what the csproj file look like?

I'm running into the same problem and it's causing my a world of pain right now. I have added these properties to the csproj file but still get the same errors.

`<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
`
and

```
  <ItemGroup>
  <Content Include="external\librets-pinvoke.dll"/>
  <Content Include="external\librets-dotnet.dll" />
</ItemGroup>
```

**Comment by abidCharlotte49er** [comment]
Here you go. It has been a while so I documented what I did back then so that it will be helpful to others. Please note our project is DotNet Core.  

[MLSCSProj.txt](https://github.com/NationalAssociationOfRealtors/libRETS/files/4381867/MLSCSProj.txt)

**Comment by kalmantri1** [comment]
@abidCharlotte49er, Do you happen to have the working dlls for both librets-net and librets-pinvoke. I am using .net core and followed the same suggestions as you stated , but I am getting this error: {"The type initializer for 'librets.libretsPINVOKE' threw an exception."}
We were using older version of librets so far and looks like somethings changed by our RETS  provider, it could be related to the TLS 1.2 support.
I appreciate if anyone else has run into this problem and have fixed it, to give some leads. Thanks in advance

**Comment by abidCharlotte49er** [comment]
Here you go try these. Make sure you drop the PINVOKE file in appropriate place. You can't add reference to that file so you need to manually drop it in the appropriate folder. Also see NO_SSL_VERIFY flag 


`RetsSession session = new RetsSession(mlsVendor.RETSUrl);
                session.SetUserAgent(mlsVendor.Useragent);
                if (!string.IsNullOrEmpty(mlsVendor.UseragentPassword))
                    session.SetUserAgentPassword(mlsVendor.UseragentPassword);//This is required for some 
                session.SetRetsVersion(RetsVersion.RETS_1_7_2);
                **session.SetModeFlags(RetsSession.MODE_NO_SSL_VERIFY);**
                session.Login(mlsVendor.Username, mlsVendor.Password);` 

[librets-dotnet.zip](https://github.com/NationalAssociationOfRealtors/libRETS/files/4919972/librets-dotnet.zip)

**Comment by kalmantri1** [comment]
Really appreciate your response. Thanks a Mil !!
