### ISSUE TITLE
C# multihreading librets and photo download 

### ISSUE THREAD

**Issue by robdob** [NationalAssociationOfRealtors/libRETS#69]
Hi,

Is It possible to use threads when downloading a listing's photos in c #, I've read several questions but have never come across a resolution.  I'm trying  to pickup the speed of my listing's download from the rets server. Any suggestions would be greatly appreciated. 

Thanks in advance.

**Comment by jazzklein** [comment]
That's a good question that, unfortunately, I can't answer. I added multi-thread support many moons ago, but that works within the native c++ and other native languages. But, I'm not a Windows developer and never had the ability to fully test it there. All I can say is give it a try.

**Comment by robdob** [comment]
Hi Mark,

 

Thanks for the answer,

 

Provided that threading is supported in C# with your lib, am I approaching this correctly, as currently its taking about 1 or 2 seconds per listing with photos to download, I’m thinking that pushing the downloading of the photos to worker threads should have a major impact in speed?

 

Do you have a little example of how the downloading of photos for an MLS listing is currently being done in c/c++ so that I can use it for reference.

 

Thanks, Rob..

**Comment by jazzklein** [comment]
I just realized I never answered this ... sorry.

I do not have an example of threaded support for fetching multiple objects, but you could try modeling after the `interleaved.cpp` example. In summary, that does an initial search looking for and returning only the `keyField` (from the metadata) for all listings matching your criteria. Once you get all the `listingIds`, you could then partition doing a separate search for each listing and then fetching the objects there. While `interleaved.cpp` is not threaded, it should give you an idea. What you need to ensure is that the server you're working with can handle multiple concurrent searches by session. In the days I was doing this work, most of the servers would not allow that.
