### ISSUE TITLE
Missing first photoObject for MRIS 

### ISSUE THREAD

**Issue by abidCharlotte49er** [NationalAssociationOfRealtors/libRETS#75]
Anyone seen this issue before. We are are not able to get first image from MRIS it always starts from index 2. Never seen this issue before. Issue is seen in RetsConnector as well. Added sample code for reference. 

As a workaround I'm thinking about accessing missing image by the index (0 or 1) Is there a document that shows how we can pull Photo objects by their index? 

Thanks in advance.  

![image](https://user-images.githubusercontent.com/2357276/56613025-c34b8a00-65e3-11e9-8db2-df15856e52df.png)

**Comment by bwolven** [comment]
There used to be a flag to ignore malformed headers.
GetObjectRequest::SetIgnoreMalformedHeaders(bool ignore)
You can try that.

**Comment by abidCharlotte49er** [comment]
Hey Bruce, Thanks You I will try this early next week and write my comments. Thank You so much for taking time and suggesting this.

**Comment by bwolven** [comment]
I've been through this before myself. It has something to do with the leading CR missing in the mime content being returned or something like that. And that effects the parsing of the first image in the set.

**Comment by jazzklein** [comment]
Some servers apparently don't follow the proper spec for MIME/Multipart. The spec says that each header must include the leading CRLF meaning that there needs to be CRCRLF<boundary> between the optional leading content and the boundary header. 

Here's what the ignore malformed headers flag does: 
```    
  if (ignoreMalformedHeaders && !(content.substr(0,2) == "\r\n"))
    {
        content = "\r\n" + content;
    }
```

**Comment by abidCharlotte49er** [comment]
Bruce, Mark 

I can confirm setting that flag did the trick. I can now get that missing image. Thank you all for looking into this and helping us resolve this. I have to see if this option impacts other MLS integration. I see in the document it is advised not to use this option.  

![image](https://user-images.githubusercontent.com/2357276/56990070-184a4b80-6b62-11e9-9302-25c7ef883fb2.png)

**Comment by bwolven** [comment]
If at all possible, you should make it a site level configuration and only use it for sites with the actual issue.
