### ISSUE TITLE
Error installing LibRets package 1.6.3 on .Net Core 3.0

### ISSUE THREAD

**Issue by carlos7649** [NationalAssociationOfRealtors/libRETS#86]
I created a new project on VS 2019 and install : PM> install-package libRets-x64 -version 1.6.3

**The errors I got are this :**

Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1701	Package 'libRETS-x64 1.6.3' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.	LibRETSGetAllListingData	C:\Users\CarlosT\source\repos\Projects\TEST\LibRETSGetAllListingData\LibRETSGetAllListingData\LibRETSGetAllListingData.csproj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Warning	MSB3270	There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Users\CarlosT\.nuget\packages\librets-x64\1.6.3\lib\net\librets-dotnet.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.	LibRETSGetAllListingData	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	2106	
![error](https://user-images.githubusercontent.com/52291031/75809523-c227d500-5d3d-11ea-9e33-8b63370dff78.jpg)

**Comment by jazzklein** [comment]
Sorry, you're going to have to find someone that can build this with Windows to support you.
