### ISSUE TITLE
1.6.1 or 1.6.3   and TLS 1.2

### ISSUE THREAD

**Issue by jgradeckimaryville** [NationalAssociationOfRealtors/libRETS#89]
Has anyone been able to get librets working with .net 2.0 or 4.x along with TLS 1.2?  My provider just switched and I'm dead in the water.

I've tried to use 1.6.1 as a direct replacement for an older version and I still get an error with unknown cipher.   

Do I need to make a code change to specify TLS 1.2?   I've updated the server to support TLS 1.2 and disable all other ciphers.   I didn't do anything with openSSL, etc.

Any thoughts would be great.  And Yes, I did see the other closed issues but nothing was helpful...

**Comment by zBestData** [comment]
Is this your problem?
https://blog.zbestdata.com/post/2019/08/19/libRETS-stops-pulling-mls-data-and-login-fails

**Comment by jgradeckimaryville** [comment]
I tried 1.6.3 which is later version but it won’t work with .net website project.  Nuget won’t install it and even manually .net won’t load the .dll

On Jul 9, 2020, at 9:46 PM, Graham <notifications@github.com> wrote:

﻿

CAUTION:This email originated outside of Maryville University. Review links and attachments carefully before opening.


Is this your problem?
https://blog.zbestdata.com/post/2019/08/19/libRETS-stops-pulling-mls-data-and-login-fails<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fblog.zbestdata.com%2fpost%2f2019%2f08%2f19%2flibRETS-stops-pulling-mls-data-and-login-fails&c=E,1,6lOYYrI14EYrzTKyoTBq65zg99LTP_y49X1RH_IdOVdxGfwMu7hDjERYlVSso51EyAOsjqmcsonmYBVDVeD72zoxc98pAVNSqAcfgZ_HG0xMd1W7pU2xZNAuRw,,&typo=1>

**Comment by zBestData** [comment]
I will help you with this if I can.  First, who is the data provider?  Is it a company like flexmls or is the MLS managing their own server privately?

have you tried setting the rest mode to mode_no_sql_verify ?  (numerical value = 8)

I presume you are using Visual Studio for development.  If nuget is not installing, probably conflict with others in project still using net 2.0

**Comment by jgradeckimaryville** [comment]
Corelogic is our provider – they removed TLS 1.0 and 1.1 support on 7/8

Yes, mode_no_ssl_verify is already set – that’s how we’ve ran for the past couple years

Trying to install 1.6.3 in VS with 4.8 framework, I get this error

The package 'libRETS-x64' tried to add a framework reference to 'librets-dotnet.dll' which was not found in the GAC. This is possibly a bug in the package.

Tried to put in the GAC but the assembly isn’t strong named.


I can add 1.6.3 to an empty project (not website) and copy over the files but then it isn’t recognized and same error about the GAC.

**Comment by zBestData** [comment]
I am running .net 4.7.2

I have attached the 64 bit nuget package from my VS Project.  You will probably need to add references to both  librets-dotnet.dll   and librets-pinvoke.dll.  If you are not able to download it, email me and I will  get it to you another way.

[libRETS-x64.1.6.3.zip](https://github.com/NationalAssociationOfRealtors/libRETS/files/4902991/libRETS-x64.1.6.3.zip)

**Comment by jgradeckimaryville** [comment]
Thanks yes, I was able to download and these are the ones I’ve been trying to add to the project.

I appreciate you taking the time on this.  It shouldn’t be this difficult.   I tried adding references to both, pinvoke denied being added saying it wasn’t a com object and then I added librets-dotnet, it displayed an empty dialog.   I have both of the files in my /bin directory and appropriate using librets;   but when I compile, still cannot find the .dlls…..something about the 64-bit as I can add the 1.6.1 version without issue.

This is a website project and I’m currently targeting 4.8 which is installed.  Also tried 4.5

Ultimately, leaning on stackoverflow…found a link which outlines 64-bit for older asp.net sites isn’t really supported per microsoft….Our app has been doing RETS for over 12 years…looks like its time for a rewrite.

**Comment by jgradeckimaryville** [comment]
Do you know…is there any reason there isn’t a 1.6.3 x86 version?

**Comment by zBestData** [comment]
You're welcome!  I have done my fair share head beating over the years and have come to have a love/hate relationship with libRETS.  It is not being supported as it once was and I think the push to replace RETS with MATRIX has a lot to do with it. As for why there isn't an x86 version.... I have no clue! 

I am running a set of API's on .Net Core, but the import is still dependent upon libRETS.  My plans are to replace libRETS with another .Net Core Project.

Before you do a rewrite, consider this project.  It is an open source MVC.Net has has most of the functionality Realtors want already built in.

https://zbestpropertymanager.com/

**Comment by cinnaman** [comment]
Does anyone have a similar link to 32 bit version of ZIP for librets-dotnet of v1.6.3? Visual Studio likes 32 bit version from past experience even on a 64 bit machine.

**Comment by jgradeckimaryville** [comment]
That’s pretty much where I think we are at.  When I get some more time I’ll download the source and see if a 32-bit compile is possible

On Jul 10, 2020, at 10:28 AM, Harman Gill <notifications@github.com> wrote:

﻿

CAUTION:This email originated outside of Maryville University. Review links and attachments carefully before opening.


Does anyone have a similar link to 32 bit version of ZIP for librets-dotnet of v1.6.3? Visual Studio likes 32 bit version from past experience even on a 64 bit machine.

**Comment by jazzklein** [comment]
Sorry guys. I've been out of the real estate business for 7 years. All the guys at NAR that used to support this project are gone. The last time I tried to find someone at NAR that was an administrator for `libRETS` this org failed (and I keep getting notices from github that they're unable to contact that NAR guys either). I stick around because I'm the last guy with write access to the project that can approve PRs and merge things.

Oh, and I'm not a Windows guy, so building and supporting libRETS on Windows is not something I can do.

That said .. if any of you Windows guys wants to update things and build whatever packages are necessary for newer versions of Windows/support libraries, I will merge any PR and build a release with those fixes (and attach the Windows binary packages for others). 

Note that with the TLS changes that happened this year, `openssl` probably needs to be refreshed to a newer version. The problem I think you're running into is that the older Windows binaries are using a version of `openssl` that doesn't include the latest ciphers and algorithms for supporting TLS 1.2.

**Comment by jgradeckimaryville** [comment]
Thanks.  I’m going to give it a whirl.  Thanks for the update on OpenSSL as well

On Jul 10, 2020, at 11:03 AM, Mark Klein <notifications@github.com> wrote:

﻿

CAUTION:This email originated outside of Maryville University. Review links and attachments carefully before opening.


Sorry guys. I've been out of the real estate business for 7 years. All the guys at NAR that used to support this project are gone. The last time I tried to find someone at NAR that was an administrator for libRETS this org failed (and I keep getting notices from github that they're unable to contact that NAR guys either). I stick around because I'm the last guy with write access to the project that can approve PRs and merge things.

Oh, and I'm not a Windows guy, so building and supporting libRETS on Windows is not something I can do.

That said .. if any of you Windows guys wants to update things and build whatever packages are necessary for newer versions of Windows/support libraries, I will merge any PR and build a release with those fixes (and attach the Windows binary packages for others).

Note that with the TLS changes that happened this year, openssl probably needs to be refreshed to a newer version. The problem I think you're running into is that the older Windows binaries are using a version of openssl that doesn't include the latest ciphers and algorithms for supporting TLS 1.2.

**Comment by zBestData** [comment]
Ran across this article.  Could it be related?
https://devblogs.microsoft.com/nuget/deprecating-tls-1-0-and-1-1-on-nuget-org/

**Comment by pstallings** [comment]
Just a note what resolved our TSL errors:
We have an in house application to import RETS data.  We were running libRETS 153 and started getting errors when Matrix changed their connection requirements.  The steps I followed:
1.	Installed libRets-x64/1.6.3
from: https://www.nuget.org/packages/libRETS-x64/1.6.3
Didn’t change error.
2.	Installed openSSL 1.1.1
from: https://slproweb.com/download/Win64OpenSSL-1_1_1g.msi
install location: C:\Program Files\OpenSSP-Win64
(other option was: OpenSSL binaries (/bin) directory)
Errors changed to: error setting certificate verify locations:
CAfile: cacert.pem
 CApath: none
3.	Downloaded cacert.pem
from: http://curl.haxx.se/ca/cacert.pem
On my development machine was able to place cert in same directory as my application executable.
On our production machine this didn’t work and I placed cert in : c:\windows\system32
Resolved error.

**Comment by roycejudd** [comment]
I was able to get it to login and run a search after installing openSSL 1.1.1, but it will not get the results.
GetCount() shows there are results but GetColumns() and HasNext() is always 0 and false.
Any ideas?

**Comment by pstallings** [comment]
No, I haven't seen that behavior before.  We've had no trouble getting data.  Perhaps a few more missing pictures than usual.  Login was the only place we noticed problems, but this code has been live for less than a day, so I'm not staking my life on anything yet.

**Comment by rpratt7opals** [comment]
My 2 cents. I was running librets v1.5.1 (I think) x32 in a VS2012 project using the SSL No Verify mode. Like others, connection attempts to a MATRIX server started failing.
I downloaded v1.6.3 (x64), migrated to VS2017, migrated client app to x64. 
Once done, I had no trouble connecting to the 2 MATRIX MLS sites we run with. Still have to use the SSL No Verify mode otherwise I get a 503 error. I did not look into the cert issue.
Many thanks to those who blazed a trail ahead of me!

**Comment by roycejudd** [comment]
What version of .NET are you using?  I went through the same process and can login but it broke the search.  I cannot get it to read through the results of any MLS.

**Comment by rpratt7opals** [comment]
Oh, I didn’t push my Target Framework forward from .Net 4.0 though I have up to 4.6.1 installed on that machine. I can try a newer version if you like.

**Comment by rpratt7opals** [comment]
Maybe this will help. I did get extracts but I got a ton of trash before I successfully connected. I didn’t notice before. Looks like this and it happens whether I connect to a MATRIX server or a different server (FNIS). The download file has the expected format – in my case Compact Format.

 

This is what my log looks like. Tedious but I don’t how better to share it.

 

* Expire in 0 ms for 6 (transfer 0x1e5ba400)

* Expire in 1 ms for 1 (transfer 0x1e5ba400)

* Expire in 0 ms for 1 (transfer 0x1e5ba400)

… goes on for many entries and then:

 

Connected to matrixrets.miborblc.com (50.17.196.26) port 443 (#0)

* ALPN, offering http/1.1

* error setting certificate verify locations, continuing anyway:

*   CAfile: cacert.pem

  CApath: none

 

>>> Sent


  _____  

[1] * TLSv1.3 (OUT), TLS handshake, Client hello (1):

>>> Sent

.. lots of trash characters including GoDaddy references and then


  _____  

  _____  

F* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):

 

>>> Sent

  BA

  _____  

�l�F�?X�7��`�+@����2F��g&Q�41�
  _____  

q�
�

�:�ᵹ��M*���!)E

�ٟH�

  _____  

  _____  

* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):

 

>>> Sent


  _____  

  _____  

(* TLSv1.2 (OUT), TLS handshake, Finished (20):

 

>>> Sent

  
:�A�����­�

<<< Received



  _____  

  _____  

  _____  

  _____  

 (* TLSv1.2 (IN), TLS handshake, Finished (20):

 

<<< Received

  
rR�D‑�L

  _____  

=��* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256

* ALPN, server accepted to use http/1.1

* Server certificate:

*  subject: OU=Domain Control Validated; CN=*.miborblc.com

*  start date: Jan 22 12:08:31 2020 GMT

*  expire date: Mar 22 17:35:02 2022 GMT

*  issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2

*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.

 

>>> Sent


  _____  

  _____  

�GET /rets/login.ashx HTTP/1.1

Host: matrixrets.miborblc.com

Accept: */*

RETS-Version: RETS/1.5

User-Agent: IndianaIAR/1.0

X-Librets-Version: 1.6.3-SNAPSHOT, libCURL - libcurl/7.64.0-DEV OpenSSL/1.1.1a WinIDN

Then the usual connection refusal for credentials.

Then the usual success for connection.

Then submit my query:

Class=Listing&Count=1&Format=COMPACT-DECODED&Limit=10&Query=(Status%3d|A)&QueryType=DMQL2&SearchType=Property&StandardNames=0* upload completely sent off: 125 out of 125 bytes

 

<<< Received

 

Then I get the 10 records I asked for (7892 available). (I retried with a 1000 records and got the 1000 records)

<RETS ReplyCode="0" ReplyText="Operation Success.">

<COUNT Records="7892" />

 


  _____  

  _____  

1bf0

<DELIMITER value = "09"/>

<COLUMNS>     AccessibilityFeatures      AccessibilityFeaturesYN                Acres     ActiveOpenHouseCount                ActualExpenses                AddressonPublicInternet             AffectedbyDisclosures  AgentRemarks  Amenities                Anchor Appliances          ApplicationFee  ApplicationLinkURL         ArchitecturalStyle            Area      AreasInterior                Assessment       AssocMaintdBldgExterior             AuctionCompanyLicenseNum    AuctionCompanyName AuctionDate                AuctionManagersLicense             AuctionManagersName                AuctionTime      AuctionType      AutoParking                AutoParkingCIN                AutoSurface       AvailableforShowing      AvailableforShowingDate             BACAmount                BackOnMarketDate        Basement           BasementDescription    BathAreas           BathsFull              BathsHalf                BathsTotal           BaySize BedroomsMU   BedsMU              BedsTotal            BuilderProjectContrName                BuildingCertification       BuildingInformation        BuildingLevels   Buildings              BuildingSize        BuildingType                BuildingUtilities BuyerAgencyCommission            CAMExpenses   CAMExpensesSF              CancelledDate   CapRate                CDOM   CeilingHeight     CeilingHeight2   CenterName      CertificationDate              CertificationRating                CertifyingOrganization   CircumstanceofSale        CircumstancesreSale      City        CloseDate           ClosePrice                CoListAgent_MUI            C

 

So something is not right and I would think it is with librets.

We are, of course, under the gun to get data.

**Comment by roycejudd** [comment]
I turned on logging and ran the exact same code using 1.5.2 and 1.6.3 and am seeing 2 different responses to search()

Using 1.5.2 the .Search() returns something like this
<RETS ReplyCode="0" ReplyText="Operation successful.">
<COUNT Records="521" />
<DELIMITER value="9" />
<COLUMNS>	FirstName	LastName	</COLUMNS>
<DATA>	John	Whited	</DATA>
<DATA>	John	Tester	</DATA>
<DATA>	John	Wallet	</DATA>
<DATA>	John	Taylor	</DATA>
<DATA>	John	Jones	</DATA>
<DATA>	John	Baughcum	</DATA>

The HasNext() loop consumes and gives you access to each column you customized in SetSelect()

Using 1.6.3 the .Search() is returning a fully formated xml string with all available columns
<?xml version="1.0" encoding="utf-8"?>
<RETS ReplyCode="0" ReplyText="Operation successful.">
  <COUNT Records="521" />
  <REData>
    <REAgents>
      <Member>
        <Member>
          <CarrierRouteCode />
          <City>West Chester</City>
          <County />
          <EmailAddress>jwhited@cinci.rr.com</EmailAddress>
          <FirstName>John</FirstName>
          <FullName>John L. Whited</FullName>

how do it get access to that xml string so we can consume it?

**Comment by rpratt7opals** [comment]
Ok. Our needs may be significantly different so I might not be much help. 

Your 1.5.2 format looks like COMPACT-DECODED which is all I need for my solution.

(From my query: Class=Listing&Count=1&Format=COMPACT-DECODED…)

Your 1.6.3 format sounds like a different download format (raw XML). 

Longtime since I had to look at the standard. Do you have it handy?

Maybe something in 1.6.3 not handling the Format value correctly for you?

**Comment by rpratt7opals** [comment]
From https://smartmls.com/wp-content/uploads/2018/10/RETS1.9-specification.pdf

I see there is a STANDARD-XML format may be available; it is not a required Format. 

The only values I see in object browser on librets-dotnet is COMPACT (0) and COMPACT-DECODED (1).

I don’t see what the enum value is for STANDARD-XML. 

 

 

From: Raymond Pratt [mailto:ray@sevenopals.com] 
Sent: Monday, July 13, 2020 7:54 PM
To: NationalAssociationOfRealtors/libRETS; NationalAssociationOfRealtors/libRETS
Cc: Comment
Subject: RE: [NationalAssociationOfRealtors/libRETS] 1.6.1 or 1.6.3 and TLS 1.2 (#89)

 

Ok. Our needs may be significantly different so I might not be much help. 

Your 1.5.2 format looks like COMPACT-DECODED which is all I need for my solution.

(From my query: Class=Listing&Count=1&Format=COMPACT-DECODED…)

Your 1.6.3 format sounds like a different download format (raw XML). 

Longtime since I had to look at the standard. Do you have it handy?

Maybe something in 1.6.3 not handling the Format value correctly for you?

**Comment by roycejudd** [comment]
thank you so much.  you're a lifesaver.  I am guessing it was set to COMPACT by default before.  As soon as I manually set it before the search everything seems to be working.

**Comment by jazzklein** [comment]
Added `SetCACertPath(std::string cacert_path)` to allow a location of your `cacert.pem` certificate chain to be provided. You'll need to find a Windows person that can help you build this if you're windows based.
