### ISSUE TITLE
Authentication errors tls1.2

### ISSUE THREAD

**Issue by billy412** [NationalAssociationOfRealtors/libRETS#90]
I've seen other posts and solutions but none of them seem to be working. i keep getting this error

<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>

My credentials are fine! any ideas? i've even installed the beta as suggested in other posts.

**Comment by zBestData** [comment]
What have your tried so far?
Is this a new login or an existing one that is not working?
Any notices regarding changes by your MLS's Data provider?

**Comment by billy412** [comment]
I installed the beta 1.6.3. Other vendors had the install work successfully. The logon is valid. It works on the rets url directly. Corelogic changed security 2 days ago

**Comment by billy412** [comment]
Other vendors simply had to change their url from http to https , but librets is having problems with that.

**Comment by zBestData** [comment]
Couple of thoughts:

1.  Don't use the beta. Use the final release
https://www.nuget.org/packages/libRETS-x64/1.6.3

2.  Have you seen this thread?  Is was opened yesterday and mentions having problems after the changes at CoreLogic
https://github.com/NationalAssociationOfRealtors/libRETS/issues/89


3.  Ran across this article while helping with #2.  Could it also be related?
https://devblogs.microsoft.com/nuget/deprecating-tls-1-0-and-1-1-on-nuget-org/

**Comment by jazzklein** [comment]
You can use the new API SetCACertPath(std::string cacert_path)` to specify a location to your `cacert.pem` bundle. You will need someone that knows Windows to help you build this for Windows.
