### ISSUE TITLE
librets won't work with RETS 1.9.0 servers

### ISSUE THREAD

**Issue by bkrets** [NationalAssociationOfRealtors/libRETS#91]
@jazzklein , when you connect to a RETS 1.9.0 server (such as bridge) retslib crashes with a message  " librets.RetsExceptionNative: Invalid RETS version string: RETS/1.9.0" .  This appears to be because 1.9.0 is not in the enums (below) and the code states that if it isn't a defined version, the RetsException "Invalid RetsVersion".  Fixing it is simple, but recompiling is hard (setting up the environment).  Could you possibly tweak this and compile the windows libraries so it doesn't crash when the RETS server response with a 1.9.0 version string?  No other changes are needed.

{
    /**
     * This is a RETS 1.0 server.
     */
    RETS_1_0,
    /**
     * This is a RETS 1.5 server.
     */
    RETS_1_5,
    /**
     * This is a RETS 1.7 server.
     */
    RETS_1_7,
    /**
     * This is a RETS 1.7.2 server.
     */
    RETS_1_7_2,
    /**
     * This is a RETS 1.8 server.
     */
    RETS_1_8,
    /**
     * This is a RETS 1.8.0 server.
     */
    RETS_1_8_0
};

**Comment by bkrets** [comment]
@jazzklein , FYI we got it to compile finally so we are good.  For anyone else dealing with Bridge vRETS servers, you will need to add a variable for RETS 1.9.0 in the enum above and recompile and it works fine.

**Comment by jazzklein** [comment]
When you tried logging in originally, what version did you send to the server? If you sent 1.8, then the server should've fallen back to the 1.8 version. The fact that it sent 1.9 makes me thing you didn't set the version properly for your login.

I think you've just introduced latent problems by simply adding the 1.9 version to the `enum` without implementing any of the 1.9 changes. The server very well could start sending you 1.9 compliant messages that `libRETS` won't be able to handle.

**Comment by bkrets** [comment]
Bridge vRETS unfortunately won’t let you set the version and won’t support anything but 1.9.0.  I checked directly with them, they say 1.9.0 is all they have and all they will support.  Their server won’t fall back to 1.8.0.  In our logs, we passed them 1.8.0, they responded 1.9.0 anyway and then librets exits.

We did change the enum and recompile and all actions we do work fine.  We aren’t using anything new since 1.7.2.  Unfortunately there wasn’t another good option unless we rebuilt on something other than librets.

**Comment by baguilar-work** [comment]
Running into the same issue. Is there any plan from NAR to pay for this update to 1.9?

**Comment by jazzklein** [comment]
Please check out the [README.](https://github.com/NationalAssociationOfRealtors/libRETS/blob/master/README.md)

I have no way of proving this quick fix will allow you to connect to a 1.9 server. Also please note that there is none of the `RETS 1.9` code in it.

**Comment by baguilar-work** [comment]
Thank you for your contribution over the years!
