### ISSUE TITLE
libRETS-x64 1.6.3 Does not work on Windows Server x64

### ISSUE THREAD

**Issue by wratte** [NationalAssociationOfRealtors/libRETS#93]
The .NET C# Library works fine on developement in x64 configuration. Unfortunatly when deployed on Windows Server the initializer seems to throw an exception everytime. The ddl used are the x64 ones.

librets-dotnet.dll
librets-pinvoke.dll

The type initializer for 'librets.RetsSession' threw an exception

**Comment by jazzklein** [comment]
You'll need to find someone knowledgable in Windows to help you resolve this. The comments I've seen in the past are either security related - something about signing a cache, or missing libraries. https://github.com/NationalAssociationOfRealtors/libRETS/issues/87 suggests downloading the redistributable C++ libraries.

**Comment by zBestData** [comment]
William,

I am a Microsoft Developer and have been running libRETS on both Windows 2016 and 2019  64 bit Servers for several years. You can reach me directly at gdavis@zbestdata.com 

Graham

**Comment by wratte** [comment]
Hi Graham,

Thanks you for taking the time. I solved this problem by installing latest Visual C++ Redistributable.

William

**Comment by zBestData** [comment]
William,

Glad to know!  Here's to success!

Graham
