### ISSUE TITLE
RetsSession.Search(query) error: Sequence contains more than one matching element

### ISSUE THREAD

**Issue by ndenkha** [NationalAssociationOfRealtors/libRETS#99]
Hi, our application code was working fine until a few days ago where the following queries starting throwing the error:
`Sequence contains more than one matching element --    at librets.RetsSession.Search(SearchRequest request)`

Query 1: 
- offset: 0
- searchType: Office
- searchClass: Office
- Query: (O_HiddenOtyID=1),(O_UpdateDate=2021-08-30T22:00:00-2021-11-10T06:29:00)

Query 2: 
- offset: 0
- searchType: Agent
- searchClass: Agent
- Query: (U_SecurityLevel=0-20),(U_UpdateDate=2021-08-30T22:00:00-2021-11-10T06:29:00)

```
    using (SearchRequest search = this.nRetsSession.CreateSearchRequest(searchType, searchClass.ToString(), query))
    {
        search.SetCountType(SearchRequest.CountType.RECORD_COUNT_ONLY);
        search.SetQueryType(SearchRequest.QueryType.DMQL2);
        search.SetStandardNames(false);
        search.SetOffset(offset);
        SearchResultSet results = this.nRetsSession.Search(search);
        return results.GetCount();
    }
```

Can someone tell us what changed on RETS side, or what changes do we need to make on ours to fix this issue?

Thanks,

Ninos

**Comment by zBestData** [comment]
Who is the MLS?  The change probably occurred there.

**Comment by ndenkha** [comment]
They sure did. I'll close this ticket. Thank you.
